/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\Nim\nim-0.18.0_x64\nim-0.18.0\dist\mingw64\bin\gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN  -IC:\Nim\nim-0.18.0_x64\nim-0.18.0\lib -o C:\Users\hkota\@Programming_projects\Nim\gui_test\nimcache\nigui_windows.o C:\Users\hkota\@Programming_projects\Nim\gui_test\nimcache\nigui_windows.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct tyObject_WndClassEx_kvawMPngbWf08knCEBUwXg tyObject_WndClassEx_kvawMPngbWf08knCEBUwXg;
typedef struct tyObject_Rect_VxivoY2vZJEZyWxDfx8tmQ tyObject_Rect_VxivoY2vZJEZyWxDfx8tmQ;
typedef struct tyObject_RGB32_eMTqFganKQ3L1Co3gEEuuA tyObject_RGB32_eMTqFganKQ3L1Co3gEEuuA;
typedef struct tyObject_Point_0LVNtwluusArrv5A6akUEA tyObject_Point_0LVNtwluusArrv5A6akUEA;
typedef struct tyObject_ScrollInfo_XvgCUpbhF0LTczEK4cBhEA tyObject_ScrollInfo_XvgCUpbhF0LTczEK4cBhEA;
typedef struct tyObject_MonitorInfo_JAzAMVJ6iqBmLjuNGHPRAA tyObject_MonitorInfo_JAzAMVJ6iqBmLjuNGHPRAA;
typedef struct tyObject_Size_Hn85q4JwVguE7xSRIlZL5A tyObject_Size_Hn85q4JwVguE7xSRIlZL5A;
typedef struct tyObject_GdiplusStartupInput_zSkasNgskGNpGAtdVxeb5w tyObject_GdiplusStartupInput_zSkasNgskGNpGAtdVxeb5w;
typedef struct tyObject_ARGB_zcvql0T8sTZjFZBZHN1Vsw tyObject_ARGB_zcvql0T8sTZjFZBZHN1Vsw;
typedef struct tyObject_RectF_4jhjakldt59cZB8eaSu3Z9aQ tyObject_RectF_4jhjakldt59cZB8eaSu3Z9aQ;
typedef struct tyObject_BitmapData_EyrbOtjHb52xJ5Z2G7h1Hg tyObject_BitmapData_EyrbOtjHb52xJ5Z2G7h1Hg;
typedef struct tyObject_OpenFileName_vYgl4eSybSoqlUe1vD9bfsw tyObject_OpenFileName_vYgl4eSybSoqlUe1vD9bfsw;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_STDCALL_PTR(void*, tyProc_sDfriKhzNlXpApkYMEo9aAA) (NCSTRING lpFileName);
typedef N_STDCALL_PTR(NI, tyProc_uryidYWkntM7ddjZSyxvyQ) (void);
typedef N_STDCALL_PTR(void*, tyProc_RJ9byCLi9cSEqbQa9a3c2uapQ) (void* pActCtx);
typedef N_STDCALL_PTR(NIM_BOOL, tyProc_TEVrjPfVIcmEMgXX5pDaEQ) (void* pActCtx, void* lpCookie);
typedef N_STDCALL_PTR(NI32, tyProc_IJ8vvlYbVRxpIZFy4xyteg) (void* lpBuffer, NI32 uSize);
typedef N_STDCALL_PTR(NI32, tyProc_7PnxmGgec69ahOw2euC0aMg) (NI32 CodePage, NI32 dwFlags, NCSTRING lpMultiByteStr, NI32 cbMultiByte, NCSTRING lpWideCharStr, NI32 cchWideChar);
typedef N_STDCALL_PTR(NI32, tyProc_aL2UbUFPf4QfHuqEKGrxGA) (NI32 CodePage, NI32 dwFlags, NCSTRING lpWideCharStr, NI32 cchWideChar, NCSTRING lpMultiByteStr, NI32 cbMultiByte, NCSTRING lpDefaultChar, void* lpUsedDefaultChar);
typedef N_STDCALL_PTR(NIM_BOOL, tyProc_QxJRx4bn6L9bQRLVIMMK69aA) (void* hMem);
typedef N_STDCALL_PTR(void*, tyProc_eh9atLjSdMtlOb372gWQgng) (NI32 uFlags, NI32 dwBytes);
typedef N_STDCALL_PTR(void, tyProc_KK7tXOLIne5LrthsNOelnQ) (void* hWnd, NCSTRING lpText, NCSTRING lpCaption, NI uType);
typedef N_STDCALL_PTR(NI16, tyProc_9aPA3Nwf3SWDJZ6PJxYy39cQ) (tyObject_WndClassEx_kvawMPngbWf08knCEBUwXg* lpwcx);
typedef N_STDCALL_PTR(void*, tyProc_LP9aVw9ak4ztwPG9cJDMN8H0g) (NI32 dwExStyle, NCSTRING lpClassName, NCSTRING lpWindowName, NI32 dwStyle, NI x, NI y, NI nWidth, NI nHeight, void* hWndParent, void* hMenu, void* hInstance, void* lpParam);
typedef N_STDCALL_PTR(NIM_BOOL, tyProc_hvPJxA5dIDCpNy33miQL8w) (void* hWnd, NI32 nCmdShow);
typedef N_STDCALL_PTR(NIM_BOOL, tyProc_Lw8wMv9cpxLt9c0yizTTxgEw) (void* hWnd, NIM_BOOL bEnable);
typedef N_STDCALL_PTR(void*, tyProc_g9af9azWSgSPo0YAXp2lXQqw) (void* hWnd, NI uMsg, void* wParam, void* lParam);
typedef N_STDCALL_PTR(NIM_BOOL, tyProc_m9bRrvNaNHombdULSq5qTgw) (void* lpMsg, void* hWnd, NI32 wMsgFilterMin, NI32 wMsgFilterMax);
typedef N_STDCALL_PTR(NIM_BOOL, tyProc_xNXc5TzahDyCD07KwdJGuw) (void* lpMsg, void* hWnd, NI32 wMsgFilterMin, NI32 wMsgFilterMax, NI32 wRemoveMsg);
typedef N_STDCALL_PTR(void*, tyProc_H8IsTnWiYEk6C6lm3VL6YA) (void* hWndChild, void* hWndNewParent);
typedef N_STDCALL_PTR(NI32, tyProc_xrKXh0KvZr9bKI9cyBIvoILg) (void* hWnd, NI32 nIndex, NI32 dwNewLong);
typedef N_STDCALL_PTR(NIM_BOOL, tyProc_7MyDqiXJmys6tSBWVwgNsA) (void* hWnd, NCSTRING lpString);
typedef N_STDCALL_PTR(NI32, tyProc_E2vEM1BUo0aogky3z9cXnGg) (void* hWnd, NCSTRING lpString, NI32 nMaxCount);
typedef N_STDCALL_PTR(NI32, tyProc_ah5wcFv3UG20t2vgXBy0Fg) (void* hWnd);
typedef N_STDCALL_PTR(NIM_BOOL, tyProc_AO9aNPNOwPeBFrb9a8L2kCyQ) (void* wnd, void* hWndInsertAfter, NI32 x, NI32 y, NI32 cx, NI32 cy, NI uFlags);
typedef N_STDCALL_PTR(NIM_BOOL, tyProc_KbCcnEWwzkNvtab9b9a8P9cfg) (void* wnd, NI32 x, NI32 y, NI32 nWidth, NI32 nHeight, NIM_BOOL bRepaint);
typedef N_STDCALL_PTR(NIM_BOOL, tyProc_ycrYbV8HnW0TXpvo7DRXHw) (void* wnd, tyObject_Rect_VxivoY2vZJEZyWxDfx8tmQ* lpRect);
typedef N_STDCALL_PTR(void*, tyProc_Fq8w9ct09bs0JvPlZzl1uIXw) (void* hWnd, NU8* lpPaint);
typedef N_STDCALL_PTR(NIM_BOOL, tyProc_cDzfAZkxY4yc5QX9bMQwQ4w) (void* hWnd, NU8* lpPaint);
typedef N_STDCALL_PTR(void*, tyProc_atNYsIZ7r4zO1EED1pT4qg) (void* hWnd, NI32 msg, void* wParam, void* lParam);
struct tyObject_RGB32_eMTqFganKQ3L1Co3gEEuuA {
NU8 red;
NU8 green;
NU8 blue;
NU8 unused;
};
typedef N_STDCALL_PTR(tyObject_RGB32_eMTqFganKQ3L1Co3gEEuuA, tyProc_gyMZMPVA3KXFO9co0rVl3pg) (NI32 nIndex);
typedef N_STDCALL_PTR(NIM_BOOL, tyProc_EbscUpNtn7ymQyYiNcdKPA) (void* hWnd, tyObject_Rect_VxivoY2vZJEZyWxDfx8tmQ* lpRect, NIM_BOOL bErase);
typedef N_STDCALL_PTR(void, tyProc_Tjolzh1w2dIIpj3oCDGPFw) (NI32 nExitCode);
typedef N_STDCALL_PTR(void*, tyProc_U9aZ9ar83F9a9ajpOLLADtIucA) (void);
typedef N_STDCALL_PTR(NIM_BOOL, tyProc_a9bPfgdb9cxALdXRBninkMCg) (NI32 uiAction, NI32 uiParam, void* pvParam, NI32 fWinIni);
typedef N_STDCALL_PTR(NIM_BOOL, tyProc_n1zxC55uBzP7aBHIOEV69bw) (void* hWnd, tyObject_Point_0LVNtwluusArrv5A6akUEA* lpPoint);
typedef N_STDCALL_PTR(NIM_BOOL, tyProc_yJxEhkneNhSPNbduQX0Uag) (tyObject_Rect_VxivoY2vZJEZyWxDfx8tmQ* lpRect, NI32 dwStyle, NIM_BOOL bMenu);
typedef N_STDCALL_PTR(void*, tyProc_ZftsZIPQj8gcvKvoQpcvfg) (void* hInstance, NCSTRING lpCursorName);
typedef N_STDCALL_PTR(NI32, tyProc_AwPs2JoHODRP5YXpT1WaKg) (void* hWnd, NI32 fnBar, tyObject_ScrollInfo_XvgCUpbhF0LTczEK4cBhEA* lpsi, NIM_BOOL fRedraw);
typedef N_STDCALL_PTR(NIM_BOOL, tyProc_F2I9aokPkcZ6AoNm7I0T2hQ) (void* hMonitor, tyObject_MonitorInfo_JAzAMVJ6iqBmLjuNGHPRAA* lpmi);
typedef N_STDCALL_PTR(void*, tyProc_hfDW1I2C9a6EXJ6KTxGSN4Q) (tyObject_Rect_VxivoY2vZJEZyWxDfx8tmQ* lprc, NI32 dwFlags);
typedef N_STDCALL_PTR(NI32, tyProc_78ER49aUeWMW9b9c9aDqn5uqBg) (NI32 nIndex);
typedef N_STDCALL_PTR(void*, tyProc_V1zid1YpKbgM30owGngEqw) (void* lpPrevWndFunc, void* hWnd, NI32 uMsg, void* wParam, void* lParam);
typedef N_STDCALL_PTR(void*, tyProc_cdKxxPL6SfeQOfhEYGGKYQ) (void* hDlg, void* hCtl, NIM_BOOL bPrevious);
typedef N_STDCALL_PTR(NIM_BOOL, tyProc_zZOSr5NyndRfg3ncLW2lOw) (NU8* lpKeyState);
typedef N_STDCALL_PTR(NI32, tyProc_caKNpCnm0IEcf29aG9aS0lzA) (NI32 wVirtKey, NI32 wScanCode, NU8* lpKeyState, NCSTRING pwszBuff, NI32 cchBuff, NI32 wFlags);
typedef N_STDCALL_PTR(NIM_BOOL, tyProc_YyRZ5fABFs9ah7yEL1XGycw) (void* hWnd, NI32 wBar, NIM_BOOL bShow);
typedef N_STDCALL_PTR(NI32, tyProc_txorxsbFke20oMz9bZMYTMA) (void* hinst, NCSTRING lpszName, NI32 uType, NI32 cxDesired, NI32 cyDesired, NI32 fuLoad);
typedef N_STDCALL_PTR(void*, tyProc_9b9camieAECIsXNP4isGEaeg) (void* hWnd, void* nIDEvent, NI32 uElapse, void* lpTimerFunc);
typedef N_STDCALL_PTR(NI32, tyProc_ARIal6jZ85aG9cEwvpjmQ1w) (void* hDC, tyObject_Rect_VxivoY2vZJEZyWxDfx8tmQ* lprc, void* hbr);
typedef N_STDCALL_PTR(NI16, tyProc_m9bO4DmYzR9c3kgmXD9bY525Q) (NI32 nVirtKey);
typedef N_STDCALL_PTR(NIM_BOOL, tyProc_9apDhvmjtCQJPsV1UbOs0Sw) (void);
typedef N_STDCALL_PTR(void*, tyProc_NlBm7il42HbX6I9bsSFz8pw) (NI32 uFormat);
typedef N_STDCALL_PTR(void*, tyProc_jhe9cc9bxEicyuAN9cLs5QbWA) (NI32 uFormat, void* hMem);
typedef N_STDCALL_PTR(NI32, tyProc_aH9bWUBLQMXdc4VL7RElsXw) (NI32 uCode, NI32 uMapType);
typedef N_STDCALL_PTR(void*, tyProc_MiNAWAS20PBNUaLlFs0zMA) (void* hWnd, NI32 nIndex);
typedef N_STDCALL_PTR(void*, tyProc_eaziYd1YyguhIEtfuwqLIg) (void* hWnd, NI32 nIndex, void* dwNewLong);
typedef N_STDCALL_PTR(NIM_BOOL, tyProc_5u9b2BwDhuCXUOCiN9aTWtQg) (void* hdc, NI32 nXStart, NI32 nYStart, NCSTRING lpString, NI32 cchString);
typedef N_STDCALL_PTR(void*, tyProc_4LwT9bck9a2TlzUEfV3KrN9ag) (tyObject_RGB32_eMTqFganKQ3L1Co3gEEuuA crColor);
typedef N_STDCALL_PTR(void*, tyProc_DxnN1hC9bU8a5qTPdgum2TQ) (NI32 fnPenStyle, NI32 nWidth, tyObject_RGB32_eMTqFganKQ3L1Co3gEEuuA crColor);
typedef N_STDCALL_PTR(void*, tyProc_yv4aPgugqLPkw9a9cgMKKgqg) (NI32 nHeight, NI32 nWidth, NI32 nEscapement, NI32 nOrientation, NI32 fnWeight, NI32 fdwItalic, NI32 fdwUnderline, NI32 fdwStrikeOut, NI32 fdwCharSet, NI32 fdwOutputPrecision, NI32 fdwClipPrecision, NI32 fdwQuality, NI32 fdwPitchAndFamily, NCSTRING lpszFace);
typedef N_STDCALL_PTR(NIM_BOOL, tyProc_2IHhNXEwn9bxlGPtlfb9bkAA) (void* hdc, NCSTRING lpString, NI32 c, tyObject_Size_Hn85q4JwVguE7xSRIlZL5A* lpSize);
typedef N_STDCALL_PTR(tyObject_RGB32_eMTqFganKQ3L1Co3gEEuuA, tyProc_Zc9bcejqy9c0dwCZschRcebA) (void* hdc, tyObject_RGB32_eMTqFganKQ3L1Co3gEEuuA crColor);
typedef N_STDCALL_PTR(NIM_BOOL, tyProc_M9aJwkjzlI6Faicvw26HU8A) (void* hdc, NI32 x, NI32 y, void* lpPoint);
typedef N_STDCALL_PTR(NIM_BOOL, tyProc_4l1DpVIfD6GxaYp3jbSJoQ) (void* hdc, NI nXEnd, NI nYEnd);
typedef N_STDCALL_PTR(NI32, tyProc_1ovKTH1spz8oqbNLsggw6g) (void* hdc, NI32 x, NI32 y, tyObject_RGB32_eMTqFganKQ3L1Co3gEEuuA crColor);
typedef N_STDCALL_PTR(NI32, tyProc_ndL2MvZ9b9bJg9cqR14Yw9cbFg) (void** token, tyObject_GdiplusStartupInput_zSkasNgskGNpGAtdVxeb5w* input, void* output);
typedef N_STDCALL_PTR(NI32, tyProc_Wa9ahPGIzu5CD49agnphkD5Q) (NCSTRING filename, void** bitmap);
typedef N_STDCALL_PTR(NI32, tyProc_Yhyafj69ci2MHhBBSfVaSIw) (void* bitmap, void** hicon);
typedef N_STDCALL_PTR(NI32, tyProc_gOjpeVmPxp0QcFSbm9bMkaA) (void* graphics, void* image, NI32 x, NI32 y, NI32 width, NI32 height);
typedef N_STDCALL_PTR(NI32, tyProc_a8UZbHjFZndEEoIZvGp2ew) (void* image, NI32* width);
typedef N_STDCALL_PTR(NI32, tyProc_rLd8v7s8pe8TAH0MJJwGOQ) (NI32 width, NI32 height, void* target, void** bitmap);
typedef N_STDCALL_PTR(NI32, tyProc_OtXqSp6qWQ7zT2ViJMliDQ) (void* bitmap, NI32 x, NI32 y, tyObject_ARGB_zcvql0T8sTZjFZBZHN1Vsw color);
typedef N_STDCALL_PTR(NI32, tyProc_IMgqvg0aDoqCH3HLn09c1dw) (void* image, NCSTRING filename, void* clsidEncoder, void* encoderParams);
typedef N_STDCALL_PTR(NI32, tyProc_Ptr9a2aRIf3Nel57TUQo9cfg) (tyObject_ARGB_zcvql0T8sTZjFZBZHN1Vsw color, void** brush);
typedef N_STDCALL_PTR(NI32, tyProc_L8P82WY9cuAysWAVFUx9bHDA) (tyObject_ARGB_zcvql0T8sTZjFZBZHN1Vsw color, float width, NI32 unit, void** pen);
typedef N_STDCALL_PTR(NI32, tyProc_15n4BX7lBEP80RXoaK7dTA) (void* graphics, NCSTRING string, NI32 length, void* font, tyObject_RectF_4jhjakldt59cZB8eaSu3Z9aQ* layoutRect, void* stringFormat, void* brush);
typedef N_STDCALL_PTR(NI32, tyProc_pu56iWRuFACgjsfME4HGRA) (void* graphics, NCSTRING string, NI32 length, void* font, tyObject_RectF_4jhjakldt59cZB8eaSu3Z9aQ* layoutRect, void* stringFormat, tyObject_RectF_4jhjakldt59cZB8eaSu3Z9aQ* boundingBox, void* codepointsFitted, void* linesFilled);
typedef N_STDCALL_PTR(NI32, tyProc_m9atr4fktDavwU2PfTzXJ1g) (void* fontFamily, float emSize, NI32 style, NI32 unit, void** font);
typedef N_STDCALL_PTR(NI32, tyProc_WqUlonnXh4d6wRmtOfLenw) (NCSTRING name, void* fontCollection, void** fontFamily);
typedef N_STDCALL_PTR(NI32, tyProc_7tBJ5HPtDJ0QCzIO7D9aijQ) (void* bitmap, tyObject_Rect_VxivoY2vZJEZyWxDfx8tmQ* rect, NI32 flags, NI32 format, tyObject_BitmapData_EyrbOtjHb52xJ5Z2G7h1Hg* lockedBitmapData);
typedef N_STDCALL_PTR(NI32, tyProc_cAWA1Uuw9cN2sneKlFj0d8w) (void* bitmap, tyObject_BitmapData_EyrbOtjHb52xJ5Z2G7h1Hg* lockedBitmapData);
typedef N_STDCALL_PTR(void, tyProc_bG0Eo9aKqHnucBdwdV7fU9cw) (void* hWnd, NIM_BOOL fAccept);
typedef N_STDCALL_PTR(NI32, tyProc_XjdpNvFfnBj2lqzibYNzUw) (void* hDrop, NU32 iFile, NCSTRING lpszFile, NI32 cch);
typedef N_STDCALL_PTR(void, tyProc_im9buRnIvptJfzdASYMEbBA) (void* hDrop);
typedef N_STDCALL_PTR(NI32, tyProc_9bXer9a4ps9aSGctILcxWReVw) (void);
typedef N_STDCALL_PTR(NIM_BOOL, tyProc_A0p29bQi5PzqJFgBRU8TV1g) (tyObject_OpenFileName_vYgl4eSybSoqlUe1vD9bfsw* lpofn);
struct tyObject_BitmapData_EyrbOtjHb52xJ5Z2G7h1Hg {
NI32 Width;
NI32 Height;
NI32 Stride;
NI32 PixelFormat;
NU8* Scan0;
void* Reserved;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_WndClassEx_kvawMPngbWf08knCEBUwXg {
NI32 cbSize;
NI32 style;
void* lpfnWndProc;
NI32 cbClsExtra;
NI32 cbWndExtra;
void* hInstance;
void* hIcon;
void* hCursor;
void* hbrBackground;
NCSTRING lpszMenuName;
NCSTRING lpszClassName;
void* hIconSm;
};
struct tyObject_Rect_VxivoY2vZJEZyWxDfx8tmQ {
NI32 left;
NI32 top;
NI32 right;
NI32 bottom;
};
struct tyObject_Point_0LVNtwluusArrv5A6akUEA {
NI32 x;
NI32 y;
};
struct tyObject_ScrollInfo_XvgCUpbhF0LTczEK4cBhEA {
NI32 cbSize;
NI32 fMask;
NI32 nMin;
NI32 nMax;
NI32 nPage;
NI32 nPos;
NI32 nTrackPos;
};
struct tyObject_MonitorInfo_JAzAMVJ6iqBmLjuNGHPRAA {
NI32 cbSize;
tyObject_Rect_VxivoY2vZJEZyWxDfx8tmQ rcMonitor;
tyObject_Rect_VxivoY2vZJEZyWxDfx8tmQ rcWork;
NI32 dwFlags;
};
struct tyObject_Size_Hn85q4JwVguE7xSRIlZL5A {
NI32 cx;
NI32 cy;
};
struct tyObject_GdiplusStartupInput_zSkasNgskGNpGAtdVxeb5w {
NI32 GdiplusVersion;
void* DebugEventCallback;
NIM_BOOL SuppressBackgroundThread;
NIM_BOOL SuppressExternalCodecs;
};
struct tyObject_ARGB_zcvql0T8sTZjFZBZHN1Vsw {
NU8 blue;
NU8 green;
NU8 red;
NU8 alpha;
};
struct tyObject_RectF_4jhjakldt59cZB8eaSu3Z9aQ {
float x;
float y;
float width;
float height;
};
struct tyObject_OpenFileName_vYgl4eSybSoqlUe1vD9bfsw {
NI32 lStructSize;
void* hwndOwner;
void* hInstance;
NCSTRING lpstrFilter;
NCSTRING lpstrCustomFilter;
NI32 nMaxCustFilter;
NI32 nFilterIndex;
NCSTRING lpstrFile;
NI32 nMaxFile;
NCSTRING lpstrFileTitle;
NI32 nMaxFileTitle;
NCSTRING lpstrInitialDir;
NCSTRING lpstrTitle;
NI32 Flags;
NI16 nFileOffset;
NI16 nFileExtension;
NCSTRING lpstrDefExt;
void* lCustData;
void* lpfnHook;
NCSTRING lpTemplateName;
};
N_LIB_PRIVATE N_NIMCALL(NI, loWord_BEDTt3KWVdVGg1xnhgCElw)(void* param);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(NI, hiWord_BEDTt3KWVdVGg1xnhgCElw_2)(void* param);
N_LIB_PRIVATE N_NIMCALL(NI, roof__quCe21GD6ES9cmTsTs9cYP7Q)(NI x, NI y);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* path);
N_NIMCALL(void*, nimGetProcAddr)(void* lib, NCSTRING name);
static N_INLINE(void, stareq__tk9bwZBdb9bO9baUcUN2AX89bQmath)(NI* x, NI y);
N_NIMCALL(NI, mulInt)(NI a, NI b);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
static void* TM_9aTFEkx0c9aDHlVGqxe09bXBQ_3;
tyProc_sDfriKhzNlXpApkYMEo9aAA Dl_114443_;
tyProc_uryidYWkntM7ddjZSyxvyQ Dl_114446_;
tyProc_RJ9byCLi9cSEqbQa9a3c2uapQ Dl_114448_;
tyProc_TEVrjPfVIcmEMgXX5pDaEQ Dl_114451_;
tyProc_IJ8vvlYbVRxpIZFy4xyteg Dl_114455_;
tyProc_7PnxmGgec69ahOw2euC0aMg Dl_114459_;
tyProc_aL2UbUFPf4QfHuqEKGrxGA Dl_114467_;
tyProc_RJ9byCLi9cSEqbQa9a3c2uapQ Dl_114477_;
tyProc_QxJRx4bn6L9bQRLVIMMK69aA Dl_114480_;
tyProc_eh9atLjSdMtlOb372gWQgng Dl_114483_;
static void* TM_9aTFEkx0c9aDHlVGqxe09bXBQ_27;
tyProc_KK7tXOLIne5LrthsNOelnQ Dl_114487_;
tyProc_KK7tXOLIne5LrthsNOelnQ Dl_114493_;
tyProc_9aPA3Nwf3SWDJZ6PJxYy39cQ Dl_114499_;
tyProc_LP9aVw9ak4ztwPG9cJDMN8H0g Dl_114503_;
tyProc_QxJRx4bn6L9bQRLVIMMK69aA Dl_114517_;
tyProc_hvPJxA5dIDCpNy33miQL8w Dl_114520_;
tyProc_Lw8wMv9cpxLt9c0yizTTxgEw Dl_114524_;
tyProc_g9af9azWSgSPo0YAXp2lXQqw Dl_114528_;
tyProc_m9bRrvNaNHombdULSq5qTgw Dl_114534_;
tyProc_xNXc5TzahDyCD07KwdJGuw Dl_114540_;
tyProc_QxJRx4bn6L9bQRLVIMMK69aA Dl_114547_;
tyProc_RJ9byCLi9cSEqbQa9a3c2uapQ Dl_114550_;
tyProc_H8IsTnWiYEk6C6lm3VL6YA Dl_114553_;
tyProc_xrKXh0KvZr9bKI9cyBIvoILg Dl_114557_;
tyProc_IJ8vvlYbVRxpIZFy4xyteg Dl_114562_;
tyProc_7MyDqiXJmys6tSBWVwgNsA Dl_114566_;
tyProc_7MyDqiXJmys6tSBWVwgNsA Dl_114570_;
tyProc_E2vEM1BUo0aogky3z9cXnGg Dl_114574_;
tyProc_ah5wcFv3UG20t2vgXBy0Fg Dl_114579_;
tyProc_QxJRx4bn6L9bQRLVIMMK69aA Dl_114582_;
tyProc_AO9aNPNOwPeBFrb9a8L2kCyQ Dl_114585_;
tyProc_KbCcnEWwzkNvtab9b9a8P9cfg Dl_114594_;
tyProc_RJ9byCLi9cSEqbQa9a3c2uapQ Dl_114602_;
tyProc_ycrYbV8HnW0TXpvo7DRXHw Dl_114605_;
tyProc_ycrYbV8HnW0TXpvo7DRXHw Dl_114610_;
tyProc_Fq8w9ct09bs0JvPlZzl1uIXw Dl_114615_;
tyProc_cDzfAZkxY4yc5QX9bMQwQ4w Dl_114620_;
tyProc_atNYsIZ7r4zO1EED1pT4qg Dl_114625_;
tyProc_atNYsIZ7r4zO1EED1pT4qg Dl_114631_;
tyProc_gyMZMPVA3KXFO9co0rVl3pg Dl_114637_;
tyProc_EbscUpNtn7ymQyYiNcdKPA Dl_114640_;
tyProc_Tjolzh1w2dIIpj3oCDGPFw Dl_114646_;
tyProc_U9aZ9ar83F9a9ajpOLLADtIucA Dl_114649_;
tyProc_a9bPfgdb9cxALdXRBninkMCg Dl_114651_;
tyProc_n1zxC55uBzP7aBHIOEV69bw Dl_114657_;
tyProc_yJxEhkneNhSPNbduQX0Uag Dl_114662_;
tyProc_ZftsZIPQj8gcvKvoQpcvfg Dl_114668_;
tyProc_AwPs2JoHODRP5YXpT1WaKg Dl_114672_;
tyProc_F2I9aokPkcZ6AoNm7I0T2hQ Dl_114679_;
tyProc_hfDW1I2C9a6EXJ6KTxGSN4Q Dl_114684_;
tyProc_78ER49aUeWMW9b9c9aDqn5uqBg Dl_114689_;
tyProc_V1zid1YpKbgM30owGngEqw Dl_114692_;
tyProc_TEVrjPfVIcmEMgXX5pDaEQ Dl_114699_;
tyProc_cdKxxPL6SfeQOfhEYGGKYQ Dl_114703_;
tyProc_RJ9byCLi9cSEqbQa9a3c2uapQ Dl_114708_;
tyProc_RJ9byCLi9cSEqbQa9a3c2uapQ Dl_114711_;
tyProc_zZOSr5NyndRfg3ncLW2lOw Dl_114714_;
tyProc_caKNpCnm0IEcf29aG9aS0lzA Dl_114718_;
tyProc_YyRZ5fABFs9ah7yEL1XGycw Dl_114727_;
tyProc_txorxsbFke20oMz9bZMYTMA Dl_114732_;
tyProc_9b9camieAECIsXNP4isGEaeg Dl_114740_;
tyProc_TEVrjPfVIcmEMgXX5pDaEQ Dl_114746_;
tyProc_ARIal6jZ85aG9cEwvpjmQ1w Dl_114750_;
tyProc_ARIal6jZ85aG9cEwvpjmQ1w Dl_114756_;
tyProc_m9bO4DmYzR9c3kgmXD9bY525Q Dl_114762_;
tyProc_QxJRx4bn6L9bQRLVIMMK69aA Dl_114765_;
tyProc_9apDhvmjtCQJPsV1UbOs0Sw Dl_114768_;
tyProc_NlBm7il42HbX6I9bsSFz8pw Dl_114770_;
tyProc_jhe9cc9bxEicyuAN9cLs5QbWA Dl_114773_;
tyProc_9apDhvmjtCQJPsV1UbOs0Sw Dl_114777_;
tyProc_aH9bWUBLQMXdc4VL7RElsXw Dl_114779_;
tyProc_MiNAWAS20PBNUaLlFs0zMA Dl_114783_;
tyProc_eaziYd1YyguhIEtfuwqLIg Dl_114787_;
static void* TM_9aTFEkx0c9aDHlVGqxe09bXBQ_157;
tyProc_QxJRx4bn6L9bQRLVIMMK69aA Dl_114801_;
tyProc_QxJRx4bn6L9bQRLVIMMK69aA Dl_114804_;
tyProc_MiNAWAS20PBNUaLlFs0zMA Dl_114807_;
tyProc_H8IsTnWiYEk6C6lm3VL6YA Dl_114811_;
tyProc_5u9b2BwDhuCXUOCiN9aTWtQg Dl_114815_;
tyProc_4LwT9bck9a2TlzUEfV3KrN9ag Dl_114822_;
tyProc_DxnN1hC9bU8a5qTPdgum2TQ Dl_114825_;
tyProc_yv4aPgugqLPkw9a9cgMKKgqg Dl_114830_;
tyProc_2IHhNXEwn9bxlGPtlfb9bkAA Dl_114846_;
tyProc_IJ8vvlYbVRxpIZFy4xyteg Dl_114853_;
tyProc_Zc9bcejqy9c0dwCZschRcebA Dl_114857_;
tyProc_Zc9bcejqy9c0dwCZschRcebA Dl_114861_;
tyProc_M9aJwkjzlI6Faicvw26HU8A Dl_114865_;
tyProc_4l1DpVIfD6GxaYp3jbSJoQ Dl_114871_;
tyProc_RJ9byCLi9cSEqbQa9a3c2uapQ Dl_114876_;
tyProc_1ovKTH1spz8oqbNLsggw6g Dl_114879_;
static void* TM_9aTFEkx0c9aDHlVGqxe09bXBQ_193;
tyProc_ndL2MvZ9b9bJg9cqR14Yw9cbFg Dl_114885_;
tyProc_Wa9ahPGIzu5CD49agnphkD5Q Dl_114892_;
tyProc_Yhyafj69ci2MHhBBSfVaSIw Dl_114897_;
tyProc_Yhyafj69ci2MHhBBSfVaSIw Dl_114902_;
tyProc_ah5wcFv3UG20t2vgXBy0Fg Dl_114907_;
tyProc_gOjpeVmPxp0QcFSbm9bMkaA Dl_114910_;
tyProc_a8UZbHjFZndEEoIZvGp2ew Dl_114918_;
tyProc_a8UZbHjFZndEEoIZvGp2ew Dl_114923_;
tyProc_rLd8v7s8pe8TAH0MJJwGOQ Dl_114928_;
tyProc_OtXqSp6qWQ7zT2ViJMliDQ Dl_114935_;
tyProc_IMgqvg0aDoqCH3HLn09c1dw Dl_114941_;
tyProc_Yhyafj69ci2MHhBBSfVaSIw Dl_114947_;
tyProc_ah5wcFv3UG20t2vgXBy0Fg Dl_114952_;
tyProc_gOjpeVmPxp0QcFSbm9bMkaA Dl_114955_;
tyProc_gOjpeVmPxp0QcFSbm9bMkaA Dl_114963_;
tyProc_gOjpeVmPxp0QcFSbm9bMkaA Dl_114971_;
tyProc_Ptr9a2aRIf3Nel57TUQo9cfg Dl_114979_;
tyProc_ah5wcFv3UG20t2vgXBy0Fg Dl_114984_;
tyProc_L8P82WY9cuAysWAVFUx9bHDA Dl_114987_;
tyProc_ah5wcFv3UG20t2vgXBy0Fg Dl_114994_;
tyProc_15n4BX7lBEP80RXoaK7dTA Dl_114997_;
tyProc_pu56iWRuFACgjsfME4HGRA Dl_115007_;
tyProc_m9atr4fktDavwU2PfTzXJ1g Dl_115020_;
tyProc_ah5wcFv3UG20t2vgXBy0Fg Dl_115028_;
tyProc_WqUlonnXh4d6wRmtOfLenw Dl_115031_;
tyProc_ah5wcFv3UG20t2vgXBy0Fg Dl_115037_;
tyProc_7tBJ5HPtDJ0QCzIO7D9aijQ Dl_115040_;
tyProc_cAWA1Uuw9cN2sneKlFj0d8w Dl_115049_;
static void* TM_9aTFEkx0c9aDHlVGqxe09bXBQ_253;
tyProc_bG0Eo9aKqHnucBdwdV7fU9cw Dl_115054_;
tyProc_XjdpNvFfnBj2lqzibYNzUw Dl_115058_;
tyProc_im9buRnIvptJfzdASYMEbBA Dl_115064_;
static void* TM_9aTFEkx0c9aDHlVGqxe09bXBQ_263;
tyProc_9bXer9a4ps9aSGctILcxWReVw Dl_115067_;
tyProc_A0p29bQi5PzqJFgBRU8TV1g Dl_115069_;
tyProc_A0p29bQi5PzqJFgBRU8TV1g Dl_115073_;
TNimType NTI_EyrbOtjHb52xJ5Z2G7h1Hg_;
extern TNimType NTI_sVg18TP9cLifHyygRe9cro9aA_;
extern TNimType NTI_a6l2JZ9a5v08DFM7EdWr9alg_;
extern TNimType NTI_vr5DoT1jILTGdRlYv1OYpw_;
STRING_LITERAL(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_5, "Kernel32.dll", 12);
STRING_LITERAL(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_6, "Kernel32.dll", 12);
STRING_LITERAL(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_29, "User32.dll", 10);
STRING_LITERAL(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_30, "User32.dll", 10);
STRING_LITERAL(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_159, "Gdi32.dll", 9);
STRING_LITERAL(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_160, "Gdi32.dll", 9);
STRING_LITERAL(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_195, "Gdiplus.dll", 11);
STRING_LITERAL(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_196, "Gdiplus.dll", 11);
STRING_LITERAL(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_255, "Shell32.dll", 11);
STRING_LITERAL(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_256, "Shell32.dll", 11);
STRING_LITERAL(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_265, "Comdlg32.dll", 12);
STRING_LITERAL(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_266, "Comdlg32.dll", 12);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(NI, loWord_BEDTt3KWVdVGg1xnhgCElw)(void* param) {
	NI result;
	nimfr_("loWord", "windows.nim");
	result = (NI)0;
	nimln_(336, "windows.nim");
	result = (NI)(((NI) (ptrdiff_t) (param)) & ((NI) 65535));
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, hiWord_BEDTt3KWVdVGg1xnhgCElw_2)(void* param) {
	NI result;
	nimfr_("hiWord", "windows.nim");
	result = (NI)0;
	nimln_(339, "windows.nim");
	result = (NI)((NI)((NU64)(((NI) (ptrdiff_t) (param))) >> (NU64)(((NI) 16))) & ((NI) 65535));
	nimln_(340, "windows.nim");
	{
		NI T3_;
		NI T6_;
		NI TM_9aTFEkx0c9aDHlVGqxe09bXBQ_2;
		T3_ = (NI)0;
		T3_ = roof__quCe21GD6ES9cmTsTs9cYP7Q(((NI) 2), ((NI) 15));
		if (!(T3_ < result)) goto LA4_;
		nimln_(341, "windows.nim");
		T6_ = (NI)0;
		T6_ = roof__quCe21GD6ES9cmTsTs9cYP7Q(((NI) 2), ((NI) 16));
		TM_9aTFEkx0c9aDHlVGqxe09bXBQ_2 = subInt(result, T6_);
		result = (NI)(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_2);
	}
	LA4_: ;
	popFrame();
	return result;
}

static N_INLINE(void, stareq__tk9bwZBdb9bO9baUcUN2AX89bQmath)(NI* x, NI y) {
	NI TM_9aTFEkx0c9aDHlVGqxe09bXBQ_273;
	nimfr_("*=", "system.nim");
	nimln_(3695, "system.nim");
	TM_9aTFEkx0c9aDHlVGqxe09bXBQ_273 = mulInt((*x), y);
	(*x) = (NI)(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_273);
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, nigui_windowsInit000)(void) {
	nimfr_("windows", "windows.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, nigui_windowsDatInit000)(void) {
static TNimNode* TM_9aTFEkx0c9aDHlVGqxe09bXBQ_274[6];
static TNimNode TM_9aTFEkx0c9aDHlVGqxe09bXBQ_0[7];
NTI_EyrbOtjHb52xJ5Z2G7h1Hg_.size = sizeof(tyObject_BitmapData_EyrbOtjHb52xJ5Z2G7h1Hg);
NTI_EyrbOtjHb52xJ5Z2G7h1Hg_.kind = 18;
NTI_EyrbOtjHb52xJ5Z2G7h1Hg_.base = 0;
NTI_EyrbOtjHb52xJ5Z2G7h1Hg_.flags = 3;
TM_9aTFEkx0c9aDHlVGqxe09bXBQ_274[0] = &TM_9aTFEkx0c9aDHlVGqxe09bXBQ_0[1];
TM_9aTFEkx0c9aDHlVGqxe09bXBQ_0[1].kind = 1;
TM_9aTFEkx0c9aDHlVGqxe09bXBQ_0[1].offset = offsetof(tyObject_BitmapData_EyrbOtjHb52xJ5Z2G7h1Hg, Width);
TM_9aTFEkx0c9aDHlVGqxe09bXBQ_0[1].typ = (&NTI_sVg18TP9cLifHyygRe9cro9aA_);
TM_9aTFEkx0c9aDHlVGqxe09bXBQ_0[1].name = "Width";
TM_9aTFEkx0c9aDHlVGqxe09bXBQ_274[1] = &TM_9aTFEkx0c9aDHlVGqxe09bXBQ_0[2];
TM_9aTFEkx0c9aDHlVGqxe09bXBQ_0[2].kind = 1;
TM_9aTFEkx0c9aDHlVGqxe09bXBQ_0[2].offset = offsetof(tyObject_BitmapData_EyrbOtjHb52xJ5Z2G7h1Hg, Height);
TM_9aTFEkx0c9aDHlVGqxe09bXBQ_0[2].typ = (&NTI_sVg18TP9cLifHyygRe9cro9aA_);
TM_9aTFEkx0c9aDHlVGqxe09bXBQ_0[2].name = "Height";
TM_9aTFEkx0c9aDHlVGqxe09bXBQ_274[2] = &TM_9aTFEkx0c9aDHlVGqxe09bXBQ_0[3];
TM_9aTFEkx0c9aDHlVGqxe09bXBQ_0[3].kind = 1;
TM_9aTFEkx0c9aDHlVGqxe09bXBQ_0[3].offset = offsetof(tyObject_BitmapData_EyrbOtjHb52xJ5Z2G7h1Hg, Stride);
TM_9aTFEkx0c9aDHlVGqxe09bXBQ_0[3].typ = (&NTI_sVg18TP9cLifHyygRe9cro9aA_);
TM_9aTFEkx0c9aDHlVGqxe09bXBQ_0[3].name = "Stride";
TM_9aTFEkx0c9aDHlVGqxe09bXBQ_274[3] = &TM_9aTFEkx0c9aDHlVGqxe09bXBQ_0[4];
TM_9aTFEkx0c9aDHlVGqxe09bXBQ_0[4].kind = 1;
TM_9aTFEkx0c9aDHlVGqxe09bXBQ_0[4].offset = offsetof(tyObject_BitmapData_EyrbOtjHb52xJ5Z2G7h1Hg, PixelFormat);
TM_9aTFEkx0c9aDHlVGqxe09bXBQ_0[4].typ = (&NTI_sVg18TP9cLifHyygRe9cro9aA_);
TM_9aTFEkx0c9aDHlVGqxe09bXBQ_0[4].name = "PixelFormat";
TM_9aTFEkx0c9aDHlVGqxe09bXBQ_274[4] = &TM_9aTFEkx0c9aDHlVGqxe09bXBQ_0[5];
TM_9aTFEkx0c9aDHlVGqxe09bXBQ_0[5].kind = 1;
TM_9aTFEkx0c9aDHlVGqxe09bXBQ_0[5].offset = offsetof(tyObject_BitmapData_EyrbOtjHb52xJ5Z2G7h1Hg, Scan0);
TM_9aTFEkx0c9aDHlVGqxe09bXBQ_0[5].typ = (&NTI_a6l2JZ9a5v08DFM7EdWr9alg_);
TM_9aTFEkx0c9aDHlVGqxe09bXBQ_0[5].name = "Scan0";
TM_9aTFEkx0c9aDHlVGqxe09bXBQ_274[5] = &TM_9aTFEkx0c9aDHlVGqxe09bXBQ_0[6];
TM_9aTFEkx0c9aDHlVGqxe09bXBQ_0[6].kind = 1;
TM_9aTFEkx0c9aDHlVGqxe09bXBQ_0[6].offset = offsetof(tyObject_BitmapData_EyrbOtjHb52xJ5Z2G7h1Hg, Reserved);
TM_9aTFEkx0c9aDHlVGqxe09bXBQ_0[6].typ = (&NTI_vr5DoT1jILTGdRlYv1OYpw_);
TM_9aTFEkx0c9aDHlVGqxe09bXBQ_0[6].name = "Reserved";
TM_9aTFEkx0c9aDHlVGqxe09bXBQ_0[0].len = 6; TM_9aTFEkx0c9aDHlVGqxe09bXBQ_0[0].kind = 2; TM_9aTFEkx0c9aDHlVGqxe09bXBQ_0[0].sons = &TM_9aTFEkx0c9aDHlVGqxe09bXBQ_274[0];
NTI_EyrbOtjHb52xJ5Z2G7h1Hg_.node = &TM_9aTFEkx0c9aDHlVGqxe09bXBQ_0[0];
if (!((TM_9aTFEkx0c9aDHlVGqxe09bXBQ_3 = nimLoadLibrary((NimStringDesc*) &TM_9aTFEkx0c9aDHlVGqxe09bXBQ_5))
)) nimLoadLibraryError((NimStringDesc*) &TM_9aTFEkx0c9aDHlVGqxe09bXBQ_6);
	Dl_114443_ = (tyProc_sDfriKhzNlXpApkYMEo9aAA) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_3, "LoadLibraryA");
	Dl_114446_ = (tyProc_uryidYWkntM7ddjZSyxvyQ) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_3, "GetLastError");
	Dl_114448_ = (tyProc_RJ9byCLi9cSEqbQa9a3c2uapQ) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_3, "CreateActCtxA");
	Dl_114451_ = (tyProc_TEVrjPfVIcmEMgXX5pDaEQ) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_3, "ActivateActCtx");
	Dl_114455_ = (tyProc_IJ8vvlYbVRxpIZFy4xyteg) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_3, "GetSystemDirectoryA");
	Dl_114459_ = (tyProc_7PnxmGgec69ahOw2euC0aMg) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_3, "MultiByteToWideChar");
	Dl_114467_ = (tyProc_aL2UbUFPf4QfHuqEKGrxGA) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_3, "WideCharToMultiByte");
	Dl_114477_ = (tyProc_RJ9byCLi9cSEqbQa9a3c2uapQ) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_3, "GlobalLock");
	Dl_114480_ = (tyProc_QxJRx4bn6L9bQRLVIMMK69aA) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_3, "GlobalUnlock");
	Dl_114483_ = (tyProc_eh9atLjSdMtlOb372gWQgng) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_3, "GlobalAlloc");
if (!((TM_9aTFEkx0c9aDHlVGqxe09bXBQ_27 = nimLoadLibrary((NimStringDesc*) &TM_9aTFEkx0c9aDHlVGqxe09bXBQ_29))
)) nimLoadLibraryError((NimStringDesc*) &TM_9aTFEkx0c9aDHlVGqxe09bXBQ_30);
	Dl_114487_ = (tyProc_KK7tXOLIne5LrthsNOelnQ) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_27, "MessageBoxA");
	Dl_114493_ = (tyProc_KK7tXOLIne5LrthsNOelnQ) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_27, "MessageBoxW");
	Dl_114499_ = (tyProc_9aPA3Nwf3SWDJZ6PJxYy39cQ) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_27, "RegisterClassExA");
	Dl_114503_ = (tyProc_LP9aVw9ak4ztwPG9cJDMN8H0g) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_27, "CreateWindowExA");
	Dl_114517_ = (tyProc_QxJRx4bn6L9bQRLVIMMK69aA) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_27, "DestroyWindow");
	Dl_114520_ = (tyProc_hvPJxA5dIDCpNy33miQL8w) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_27, "ShowWindow");
	Dl_114524_ = (tyProc_Lw8wMv9cpxLt9c0yizTTxgEw) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_27, "EnableWindow");
	Dl_114528_ = (tyProc_g9af9azWSgSPo0YAXp2lXQqw) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_27, "DefWindowProcA");
	Dl_114534_ = (tyProc_m9bRrvNaNHombdULSq5qTgw) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_27, "GetMessageA");
	Dl_114540_ = (tyProc_xNXc5TzahDyCD07KwdJGuw) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_27, "PeekMessageA");
	Dl_114547_ = (tyProc_QxJRx4bn6L9bQRLVIMMK69aA) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_27, "TranslateMessage");
	Dl_114550_ = (tyProc_RJ9byCLi9cSEqbQa9a3c2uapQ) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_27, "DispatchMessageA");
	Dl_114553_ = (tyProc_H8IsTnWiYEk6C6lm3VL6YA) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_27, "SetParent");
	Dl_114557_ = (tyProc_xrKXh0KvZr9bKI9cyBIvoILg) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_27, "SetWindowLongA");
	Dl_114562_ = (tyProc_IJ8vvlYbVRxpIZFy4xyteg) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_27, "GetWindowLongA");
	Dl_114566_ = (tyProc_7MyDqiXJmys6tSBWVwgNsA) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_27, "SetWindowTextA");
	Dl_114570_ = (tyProc_7MyDqiXJmys6tSBWVwgNsA) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_27, "SetWindowTextW");
	Dl_114574_ = (tyProc_E2vEM1BUo0aogky3z9cXnGg) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_27, "GetWindowTextW");
	Dl_114579_ = (tyProc_ah5wcFv3UG20t2vgXBy0Fg) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_27, "GetWindowTextLengthW");
	Dl_114582_ = (tyProc_QxJRx4bn6L9bQRLVIMMK69aA) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_27, "UpdateWindow");
	Dl_114585_ = (tyProc_AO9aNPNOwPeBFrb9a8L2kCyQ) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_27, "SetWindowPos");
	Dl_114594_ = (tyProc_KbCcnEWwzkNvtab9b9a8P9cfg) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_27, "MoveWindow");
	Dl_114602_ = (tyProc_RJ9byCLi9cSEqbQa9a3c2uapQ) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_27, "SetFocus");
	Dl_114605_ = (tyProc_ycrYbV8HnW0TXpvo7DRXHw) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_27, "GetWindowRect");
	Dl_114610_ = (tyProc_ycrYbV8HnW0TXpvo7DRXHw) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_27, "GetClientRect");
	Dl_114615_ = (tyProc_Fq8w9ct09bs0JvPlZzl1uIXw) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_27, "BeginPaint");
	Dl_114620_ = (tyProc_cDzfAZkxY4yc5QX9bMQwQ4w) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_27, "EndPaint");
	Dl_114625_ = (tyProc_atNYsIZ7r4zO1EED1pT4qg) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_27, "SendMessageA");
	Dl_114631_ = (tyProc_atNYsIZ7r4zO1EED1pT4qg) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_27, "PostMessageA");
	Dl_114637_ = (tyProc_gyMZMPVA3KXFO9co0rVl3pg) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_27, "GetSysColor");
	Dl_114640_ = (tyProc_EbscUpNtn7ymQyYiNcdKPA) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_27, "InvalidateRect");
	Dl_114646_ = (tyProc_Tjolzh1w2dIIpj3oCDGPFw) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_27, "PostQuitMessage");
	Dl_114649_ = (tyProc_U9aZ9ar83F9a9ajpOLLADtIucA) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_27, "GetDesktopWindow");
	Dl_114651_ = (tyProc_a9bPfgdb9cxALdXRBninkMCg) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_27, "SystemParametersInfoA");
	Dl_114657_ = (tyProc_n1zxC55uBzP7aBHIOEV69bw) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_27, "ClientToScreen");
	Dl_114662_ = (tyProc_yJxEhkneNhSPNbduQX0Uag) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_27, "AdjustWindowRect");
	Dl_114668_ = (tyProc_ZftsZIPQj8gcvKvoQpcvfg) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_27, "LoadCursorA");
	Dl_114672_ = (tyProc_AwPs2JoHODRP5YXpT1WaKg) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_27, "SetScrollInfo");
	Dl_114679_ = (tyProc_F2I9aokPkcZ6AoNm7I0T2hQ) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_27, "GetMonitorInfoA");
	Dl_114684_ = (tyProc_hfDW1I2C9a6EXJ6KTxGSN4Q) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_27, "MonitorFromRect");
	Dl_114689_ = (tyProc_78ER49aUeWMW9b9c9aDqn5uqBg) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_27, "GetSystemMetrics");
	Dl_114692_ = (tyProc_V1zid1YpKbgM30owGngEqw) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_27, "CallWindowProcW");
	Dl_114699_ = (tyProc_TEVrjPfVIcmEMgXX5pDaEQ) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_27, "IsDialogMessageW");
	Dl_114703_ = (tyProc_cdKxxPL6SfeQOfhEYGGKYQ) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_27, "GetNextDlgTabItem");
	Dl_114708_ = (tyProc_RJ9byCLi9cSEqbQa9a3c2uapQ) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_27, "GetParent");
	Dl_114711_ = (tyProc_RJ9byCLi9cSEqbQa9a3c2uapQ) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_27, "GetDC");
	Dl_114714_ = (tyProc_zZOSr5NyndRfg3ncLW2lOw) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_27, "GetKeyboardState");
	Dl_114718_ = (tyProc_caKNpCnm0IEcf29aG9aS0lzA) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_27, "ToUnicode");
	Dl_114727_ = (tyProc_YyRZ5fABFs9ah7yEL1XGycw) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_27, "ShowScrollBar");
	Dl_114732_ = (tyProc_txorxsbFke20oMz9bZMYTMA) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_27, "LoadImageW");
	Dl_114740_ = (tyProc_9b9camieAECIsXNP4isGEaeg) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_27, "SetTimer");
	Dl_114746_ = (tyProc_TEVrjPfVIcmEMgXX5pDaEQ) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_27, "KillTimer");
	Dl_114750_ = (tyProc_ARIal6jZ85aG9cEwvpjmQ1w) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_27, "FillRect");
	Dl_114756_ = (tyProc_ARIal6jZ85aG9cEwvpjmQ1w) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_27, "FrameRect");
	Dl_114762_ = (tyProc_m9bO4DmYzR9c3kgmXD9bY525Q) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_27, "GetKeyState");
	Dl_114765_ = (tyProc_QxJRx4bn6L9bQRLVIMMK69aA) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_27, "OpenClipboard");
	Dl_114768_ = (tyProc_9apDhvmjtCQJPsV1UbOs0Sw) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_27, "CloseClipboard");
	Dl_114770_ = (tyProc_NlBm7il42HbX6I9bsSFz8pw) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_27, "GetClipboardData");
	Dl_114773_ = (tyProc_jhe9cc9bxEicyuAN9cLs5QbWA) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_27, "SetClipboardData");
	Dl_114777_ = (tyProc_9apDhvmjtCQJPsV1UbOs0Sw) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_27, "EmptyClipboard");
	Dl_114779_ = (tyProc_aH9bWUBLQMXdc4VL7RElsXw) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_27, "MapVirtualKeyW");
	Dl_114783_ = (tyProc_MiNAWAS20PBNUaLlFs0zMA) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_27, "GetWindowLongPtrW");
	Dl_114787_ = (tyProc_eaziYd1YyguhIEtfuwqLIg) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_27, "SetWindowLongPtrW");
if (!((TM_9aTFEkx0c9aDHlVGqxe09bXBQ_157 = nimLoadLibrary((NimStringDesc*) &TM_9aTFEkx0c9aDHlVGqxe09bXBQ_159))
)) nimLoadLibraryError((NimStringDesc*) &TM_9aTFEkx0c9aDHlVGqxe09bXBQ_160);
	Dl_114801_ = (tyProc_QxJRx4bn6L9bQRLVIMMK69aA) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_157, "DeleteDC");
	Dl_114804_ = (tyProc_QxJRx4bn6L9bQRLVIMMK69aA) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_157, "DeleteObject");
	Dl_114807_ = (tyProc_MiNAWAS20PBNUaLlFs0zMA) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_157, "GetCurrentObject");
	Dl_114811_ = (tyProc_H8IsTnWiYEk6C6lm3VL6YA) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_157, "SelectObject");
	Dl_114815_ = (tyProc_5u9b2BwDhuCXUOCiN9aTWtQg) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_157, "TextOutW");
	Dl_114822_ = (tyProc_4LwT9bck9a2TlzUEfV3KrN9ag) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_157, "CreateSolidBrush");
	Dl_114825_ = (tyProc_DxnN1hC9bU8a5qTPdgum2TQ) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_157, "CreatePen");
	Dl_114830_ = (tyProc_yv4aPgugqLPkw9a9cgMKKgqg) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_157, "CreateFontA");
	Dl_114846_ = (tyProc_2IHhNXEwn9bxlGPtlfb9bkAA) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_157, "GetTextExtentPoint32W");
	Dl_114853_ = (tyProc_IJ8vvlYbVRxpIZFy4xyteg) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_157, "SetBkMode");
	Dl_114857_ = (tyProc_Zc9bcejqy9c0dwCZschRcebA) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_157, "SetTextColor");
	Dl_114861_ = (tyProc_Zc9bcejqy9c0dwCZschRcebA) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_157, "SetBkColor");
	Dl_114865_ = (tyProc_M9aJwkjzlI6Faicvw26HU8A) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_157, "MoveToEx");
	Dl_114871_ = (tyProc_4l1DpVIfD6GxaYp3jbSJoQ) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_157, "LineTo");
	Dl_114876_ = (tyProc_RJ9byCLi9cSEqbQa9a3c2uapQ) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_157, "CreateCompatibleDC");
	Dl_114879_ = (tyProc_1ovKTH1spz8oqbNLsggw6g) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_157, "SetPixel");
if (!((TM_9aTFEkx0c9aDHlVGqxe09bXBQ_193 = nimLoadLibrary((NimStringDesc*) &TM_9aTFEkx0c9aDHlVGqxe09bXBQ_195))
)) nimLoadLibraryError((NimStringDesc*) &TM_9aTFEkx0c9aDHlVGqxe09bXBQ_196);
	Dl_114885_ = (tyProc_ndL2MvZ9b9bJg9cqR14Yw9cbFg) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_193, "GdiplusStartup");
	Dl_114892_ = (tyProc_Wa9ahPGIzu5CD49agnphkD5Q) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_193, "GdipCreateBitmapFromFile");
	Dl_114897_ = (tyProc_Yhyafj69ci2MHhBBSfVaSIw) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_193, "GdipCreateHICONFromBitmap");
	Dl_114902_ = (tyProc_Yhyafj69ci2MHhBBSfVaSIw) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_193, "GdipCreateFromHDC");
	Dl_114907_ = (tyProc_ah5wcFv3UG20t2vgXBy0Fg) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_193, "GdipDeleteGraphics");
	Dl_114910_ = (tyProc_gOjpeVmPxp0QcFSbm9bMkaA) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_193, "GdipDrawImageRectI");
	Dl_114918_ = (tyProc_a8UZbHjFZndEEoIZvGp2ew) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_193, "GdipGetImageWidth");
	Dl_114923_ = (tyProc_a8UZbHjFZndEEoIZvGp2ew) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_193, "GdipGetImageHeight");
	Dl_114928_ = (tyProc_rLd8v7s8pe8TAH0MJJwGOQ) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_193, "GdipCreateBitmapFromGraphics");
	Dl_114935_ = (tyProc_OtXqSp6qWQ7zT2ViJMliDQ) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_193, "GdipBitmapSetPixel");
	Dl_114941_ = (tyProc_IMgqvg0aDoqCH3HLn09c1dw) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_193, "GdipSaveImageToFile");
	Dl_114947_ = (tyProc_Yhyafj69ci2MHhBBSfVaSIw) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_193, "GdipGetImageGraphicsContext");
	Dl_114952_ = (tyProc_ah5wcFv3UG20t2vgXBy0Fg) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_193, "GdipDisposeImage");
	Dl_114955_ = (tyProc_gOjpeVmPxp0QcFSbm9bMkaA) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_193, "GdipFillRectangleI");
	Dl_114963_ = (tyProc_gOjpeVmPxp0QcFSbm9bMkaA) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_193, "GdipDrawRectangleI");
	Dl_114971_ = (tyProc_gOjpeVmPxp0QcFSbm9bMkaA) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_193, "GdipDrawLineI");
	Dl_114979_ = (tyProc_Ptr9a2aRIf3Nel57TUQo9cfg) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_193, "GdipCreateSolidFill");
	Dl_114984_ = (tyProc_ah5wcFv3UG20t2vgXBy0Fg) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_193, "GdipDeleteBrush");
	Dl_114987_ = (tyProc_L8P82WY9cuAysWAVFUx9bHDA) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_193, "GdipCreatePen1");
	Dl_114994_ = (tyProc_ah5wcFv3UG20t2vgXBy0Fg) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_193, "GdipDeletePen");
	Dl_114997_ = (tyProc_15n4BX7lBEP80RXoaK7dTA) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_193, "GdipDrawString");
	Dl_115007_ = (tyProc_pu56iWRuFACgjsfME4HGRA) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_193, "GdipMeasureString");
	Dl_115020_ = (tyProc_m9atr4fktDavwU2PfTzXJ1g) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_193, "GdipCreateFont");
	Dl_115028_ = (tyProc_ah5wcFv3UG20t2vgXBy0Fg) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_193, "GdipDeleteFont");
	Dl_115031_ = (tyProc_WqUlonnXh4d6wRmtOfLenw) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_193, "GdipCreateFontFamilyFromName");
	Dl_115037_ = (tyProc_ah5wcFv3UG20t2vgXBy0Fg) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_193, "GdipDeleteFontFamily");
	Dl_115040_ = (tyProc_7tBJ5HPtDJ0QCzIO7D9aijQ) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_193, "GdipBitmapLockBits");
	Dl_115049_ = (tyProc_cAWA1Uuw9cN2sneKlFj0d8w) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_193, "GdipBitmapUnlockBits");
if (!((TM_9aTFEkx0c9aDHlVGqxe09bXBQ_253 = nimLoadLibrary((NimStringDesc*) &TM_9aTFEkx0c9aDHlVGqxe09bXBQ_255))
)) nimLoadLibraryError((NimStringDesc*) &TM_9aTFEkx0c9aDHlVGqxe09bXBQ_256);
	Dl_115054_ = (tyProc_bG0Eo9aKqHnucBdwdV7fU9cw) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_253, "DragAcceptFiles");
	Dl_115058_ = (tyProc_XjdpNvFfnBj2lqzibYNzUw) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_253, "DragQueryFileW");
	Dl_115064_ = (tyProc_im9buRnIvptJfzdASYMEbBA) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_253, "DragFinish");
if (!((TM_9aTFEkx0c9aDHlVGqxe09bXBQ_263 = nimLoadLibrary((NimStringDesc*) &TM_9aTFEkx0c9aDHlVGqxe09bXBQ_265))
)) nimLoadLibraryError((NimStringDesc*) &TM_9aTFEkx0c9aDHlVGqxe09bXBQ_266);
	Dl_115067_ = (tyProc_9bXer9a4ps9aSGctILcxWReVw) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_263, "CommDlgExtendedError");
	Dl_115069_ = (tyProc_A0p29bQi5PzqJFgBRU8TV1g) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_263, "GetOpenFileNameW");
	Dl_115073_ = (tyProc_A0p29bQi5PzqJFgBRU8TV1g) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_263, "GetSaveFileNameW");
}

