/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\Nim\nim-0.18.0_x64\nim-0.18.0\dist\mingw64\bin\gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN  -IC:\Nim\nim-0.18.0_x64\nim-0.18.0\lib -o C:\Users\hkota\@Programming_projects\Nim\gui_test\nimcache\stdlib_unicode.o C:\Users\hkota\@Programming_projects\Nim\gui_test\nimcache\stdlib_unicode.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tySequence_48JTohSgTy339bRxHzUD8KA tySequence_48JTohSgTy339bRxHzUD8KA;
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ {
NI Field0;
NI Field1;
};
struct tySequence_48JTohSgTy339bRxHzUD8KA {
  TGenericSeq Sup;
  NI32 data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(tySequence_48JTohSgTy339bRxHzUD8KA*, newSeq_eYYHkXwVzOzgg15yEr5XtA)(NI len);
N_LIB_PRIVATE N_NIMCALL(tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ, runeReverseOffset_0YT8d2knu9a0zJ2Qi8H3lsw)(NimStringDesc* s, NI rev);
N_LIB_PRIVATE N_NIMCALL(NI, runeLenAt_8Ayuto32FxMnanfOP52vKg)(NimStringDesc* s, NI i);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_LIB_PRIVATE N_NIMCALL(NI, runeOffset_VmqqfobaPIVf6yXE36KGjA)(NimStringDesc* s, NI pos, NI start);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
STRING_LITERAL(TM_e1RUVS0Bw7xmj9cnDPXLJMQ_9, "", 0);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(NI, runeLenAt_8Ayuto32FxMnanfOP52vKg)(NimStringDesc* s, NI i) {
	NI result;
	nimfr_("runeLenAt", "unicode.nim");
	result = (NI)0;
	nimln_(44, "unicode.nim");
	{
		if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
		if (!((NU64)(((NU8)(s->data[i]))) <= (NU64)(((NI) 127)))) goto LA3_;
		result = ((NI) 1);
	}
	goto LA1_;
	LA3_: ;
	{
		nimln_(45, "unicode.nim");
		if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
		if (!((NI)((NU64)(((NU8)(s->data[i]))) >> (NU64)(((NI) 5))) == ((NI) 6))) goto LA6_;
		result = ((NI) 2);
	}
	goto LA1_;
	LA6_: ;
	{
		nimln_(46, "unicode.nim");
		if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
		if (!((NI)((NU64)(((NU8)(s->data[i]))) >> (NU64)(((NI) 4))) == ((NI) 14))) goto LA9_;
		result = ((NI) 3);
	}
	goto LA1_;
	LA9_: ;
	{
		nimln_(47, "unicode.nim");
		if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
		if (!((NI)((NU64)(((NU8)(s->data[i]))) >> (NU64)(((NI) 3))) == ((NI) 30))) goto LA12_;
		result = ((NI) 4);
	}
	goto LA1_;
	LA12_: ;
	{
		nimln_(48, "unicode.nim");
		if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
		if (!((NI)((NU64)(((NU8)(s->data[i]))) >> (NU64)(((NI) 2))) == ((NI) 62))) goto LA15_;
		result = ((NI) 5);
	}
	goto LA1_;
	LA15_: ;
	{
		nimln_(49, "unicode.nim");
		if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
		if (!((NI)((NU64)(((NU8)(s->data[i]))) >> (NU64)(((NI) 1))) == ((NI) 126))) goto LA18_;
		result = ((NI) 6);
	}
	goto LA1_;
	LA18_: ;
	{
		nimln_(50, "unicode.nim");
		result = ((NI) 1);
	}
	LA1_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ, runeReverseOffset_0YT8d2knu9a0zJ2Qi8H3lsw)(NimStringDesc* s, NI rev) {
	tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ result;
	NI a;
	NI o;
	NI x;
	NI TM_e1RUVS0Bw7xmj9cnDPXLJMQ_6;
	nimfr_("runeReverseOffset", "unicode.nim");
{	memset((void*)(&result), 0, sizeof(result));
	nimln_(272, "unicode.nim");
	a = ((NI) (rev));
	nimln_(273, "unicode.nim");
	o = ((NI) 0);
	nimln_(274, "unicode.nim");
	x = ((NI) 0);
	{
		nimln_(275, "unicode.nim");
		while (1) {
			NI r;
			NI TM_e1RUVS0Bw7xmj9cnDPXLJMQ_2;
			NI TM_e1RUVS0Bw7xmj9cnDPXLJMQ_4;
			if (!(o < (s ? s->Sup.len : 0))) goto LA2;
			nimln_(276, "unicode.nim");
			r = runeLenAt_8Ayuto32FxMnanfOP52vKg(s, ((NI)chckRange(o, ((NI) 0), ((NI) IL64(9223372036854775807)))));
			nimln_(277, "unicode.nim");
			TM_e1RUVS0Bw7xmj9cnDPXLJMQ_2 = addInt(o, r);
			o = (NI)(TM_e1RUVS0Bw7xmj9cnDPXLJMQ_2);
			nimln_(278, "unicode.nim");
			{
				NI TM_e1RUVS0Bw7xmj9cnDPXLJMQ_3;
				if (!(a < ((NI) 0))) goto LA5_;
				nimln_(279, "unicode.nim");
				TM_e1RUVS0Bw7xmj9cnDPXLJMQ_3 = addInt(x, r);
				x = (NI)(TM_e1RUVS0Bw7xmj9cnDPXLJMQ_3);
			}
			LA5_: ;
			nimln_(280, "unicode.nim");
			TM_e1RUVS0Bw7xmj9cnDPXLJMQ_4 = subInt(a, ((NI) 1));
			a = (NI)(TM_e1RUVS0Bw7xmj9cnDPXLJMQ_4);
		} LA2: ;
	}
	nimln_(282, "unicode.nim");
	{
		NI TM_e1RUVS0Bw7xmj9cnDPXLJMQ_5;
		if (!(((NI) 0) < a)) goto LA9_;
		nimln_(283, "unicode.nim");
		if (a == (IL64(-9223372036854775807) - IL64(1))) raiseOverflow();
		result.Field0 = ((NI64)-(a));
		TM_e1RUVS0Bw7xmj9cnDPXLJMQ_5 = subInt(((NI) (rev)), a);
		result.Field1 = (NI)(TM_e1RUVS0Bw7xmj9cnDPXLJMQ_5);
		goto BeforeRet_;
	}
	LA9_: ;
	nimln_(284, "unicode.nim");
	result.Field0 = x;
	if (a == (IL64(-9223372036854775807) - IL64(1))) raiseOverflow();
	TM_e1RUVS0Bw7xmj9cnDPXLJMQ_6 = addInt(((NI64)-(a)), ((NI) (rev)));
	result.Field1 = (NI)(TM_e1RUVS0Bw7xmj9cnDPXLJMQ_6);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, runeOffset_VmqqfobaPIVf6yXE36KGjA)(NimStringDesc* s, NI pos, NI start) {
	NI result;
	NI i;
	NI o;
	nimfr_("runeOffset", "unicode.nim");
{	result = (NI)0;
	nimln_(234, "unicode.nim");
	i = ((NI) 0);
	nimln_(235, "unicode.nim");
	o = start;
	{
		nimln_(236, "unicode.nim");
		while (1) {
			NI T3_;
			NI TM_e1RUVS0Bw7xmj9cnDPXLJMQ_10;
			NI TM_e1RUVS0Bw7xmj9cnDPXLJMQ_11;
			if (!(i < ((NI) (pos)))) goto LA2;
			nimln_(237, "unicode.nim");
			T3_ = (NI)0;
			T3_ = runeLenAt_8Ayuto32FxMnanfOP52vKg(s, o);
			TM_e1RUVS0Bw7xmj9cnDPXLJMQ_10 = addInt(o, ((NI)chckRange(T3_, ((NI) 0), ((NI) IL64(9223372036854775807)))));
			if (TM_e1RUVS0Bw7xmj9cnDPXLJMQ_10 < 0 || TM_e1RUVS0Bw7xmj9cnDPXLJMQ_10 > IL64(9223372036854775807)) raiseOverflow();
			o = (NI)(TM_e1RUVS0Bw7xmj9cnDPXLJMQ_10);
			nimln_(238, "unicode.nim");
			{
				if (!((s ? s->Sup.len : 0) <= ((NI) (o)))) goto LA6_;
				nimln_(239, "unicode.nim");
				result = ((NI) -1);
				goto BeforeRet_;
			}
			LA6_: ;
			nimln_(240, "unicode.nim");
			TM_e1RUVS0Bw7xmj9cnDPXLJMQ_11 = addInt(i, ((NI) 1));
			i = (NI)(TM_e1RUVS0Bw7xmj9cnDPXLJMQ_11);
		} LA2: ;
	}
	nimln_(241, "unicode.nim");
	result = ((NI) (o));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, runeSubStr_UlchVxVCtLbl0rRbUzNKXA)(NimStringDesc* s, NI pos, NI len) {
	NimStringDesc* result;
	nimfr_("runeSubStr", "unicode.nim");
	result = (NimStringDesc*)0;
	nimln_(293, "unicode.nim");
	{
		tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ T5_;
		NI o;
		NI rl;
		if (!(pos < ((NI) 0))) goto LA3_;
		nimln_(294, "unicode.nim");
		if (pos == (IL64(-9223372036854775807) - IL64(1))) raiseOverflow();
		T5_ = runeReverseOffset_0YT8d2knu9a0zJ2Qi8H3lsw(s, ((NI)chckRange(((NI64)-(pos)), ((NI) 1), ((NI) IL64(9223372036854775807)))));
		o = T5_.Field0;
		rl = T5_.Field1;
		nimln_(295, "unicode.nim");
		{
			NI TM_e1RUVS0Bw7xmj9cnDPXLJMQ_7;
			if (!(rl <= len)) goto LA8_;
			nimln_(296, "unicode.nim");
			TM_e1RUVS0Bw7xmj9cnDPXLJMQ_7 = subInt((s ? s->Sup.len : 0), ((NI) 1));
			result = copyStrLast(s, o, (NI)(TM_e1RUVS0Bw7xmj9cnDPXLJMQ_7));
		}
		goto LA6_;
		LA8_: ;
		{
			NI e;
			NI TM_e1RUVS0Bw7xmj9cnDPXLJMQ_8;
			nimln_(297, "unicode.nim");
			if (!(len < ((NI) 0))) goto LA11_;
			nimln_(298, "unicode.nim");
			TM_e1RUVS0Bw7xmj9cnDPXLJMQ_8 = addInt(rl, len);
			e = (NI)(TM_e1RUVS0Bw7xmj9cnDPXLJMQ_8);
			nimln_(299, "unicode.nim");
			{
				if (!(e < ((NI) 0))) goto LA15_;
				nimln_(300, "unicode.nim");
				result = copyString(((NimStringDesc*) &TM_e1RUVS0Bw7xmj9cnDPXLJMQ_9));
			}
			goto LA13_;
			LA15_: ;
			{
				NI TM_e1RUVS0Bw7xmj9cnDPXLJMQ_12;
				NI TM_e1RUVS0Bw7xmj9cnDPXLJMQ_13;
				NI T18_;
				NI TM_e1RUVS0Bw7xmj9cnDPXLJMQ_14;
				nimln_(302, "unicode.nim");
				TM_e1RUVS0Bw7xmj9cnDPXLJMQ_12 = addInt(rl, pos);
				TM_e1RUVS0Bw7xmj9cnDPXLJMQ_13 = subInt(e, (NI)(TM_e1RUVS0Bw7xmj9cnDPXLJMQ_12));
				T18_ = (NI)0;
				T18_ = runeOffset_VmqqfobaPIVf6yXE36KGjA(s, ((NI)chckRange((NI)(TM_e1RUVS0Bw7xmj9cnDPXLJMQ_13), ((NI) 0), ((NI) IL64(9223372036854775807)))), ((NI)chckRange(o, ((NI) 0), ((NI) IL64(9223372036854775807)))));
				TM_e1RUVS0Bw7xmj9cnDPXLJMQ_14 = subInt(T18_, ((NI) 1));
				result = copyStrLast(s, o, (NI)(TM_e1RUVS0Bw7xmj9cnDPXLJMQ_14));
			}
			LA13_: ;
		}
		goto LA6_;
		LA11_: ;
		{
			NI T20_;
			NI TM_e1RUVS0Bw7xmj9cnDPXLJMQ_15;
			nimln_(304, "unicode.nim");
			T20_ = (NI)0;
			T20_ = runeOffset_VmqqfobaPIVf6yXE36KGjA(s, ((NI)chckRange(len, ((NI) 0), ((NI) IL64(9223372036854775807)))), ((NI)chckRange(o, ((NI) 0), ((NI) IL64(9223372036854775807)))));
			TM_e1RUVS0Bw7xmj9cnDPXLJMQ_15 = subInt(T20_, ((NI) 1));
			result = copyStrLast(s, o, (NI)(TM_e1RUVS0Bw7xmj9cnDPXLJMQ_15));
		}
		LA6_: ;
	}
	goto LA1_;
	LA3_: ;
	{
		NI o_2;
		nimln_(306, "unicode.nim");
		o_2 = runeOffset_VmqqfobaPIVf6yXE36KGjA(s, ((NI)chckRange(pos, ((NI) 0), ((NI) IL64(9223372036854775807)))), ((NI) 0));
		nimln_(307, "unicode.nim");
		{
			if (!(o_2 < ((NI) 0))) goto LA24_;
			nimln_(308, "unicode.nim");
			result = copyString(((NimStringDesc*) &TM_e1RUVS0Bw7xmj9cnDPXLJMQ_9));
		}
		goto LA22_;
		LA24_: ;
		{
			NI TM_e1RUVS0Bw7xmj9cnDPXLJMQ_16;
			nimln_(309, "unicode.nim");
			if (!(len == ((NI) IL64(9223372036854775807)))) goto LA27_;
			nimln_(310, "unicode.nim");
			TM_e1RUVS0Bw7xmj9cnDPXLJMQ_16 = subInt((s ? s->Sup.len : 0), ((NI) 1));
			result = copyStrLast(s, o_2, (NI)(TM_e1RUVS0Bw7xmj9cnDPXLJMQ_16));
		}
		goto LA22_;
		LA27_: ;
		{
			tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ T32_;
			NI e_2;
			NI rl_2;
			nimln_(311, "unicode.nim");
			if (!(len < ((NI) 0))) goto LA30_;
			nimln_(312, "unicode.nim");
			if (len == (IL64(-9223372036854775807) - IL64(1))) raiseOverflow();
			T32_ = runeReverseOffset_0YT8d2knu9a0zJ2Qi8H3lsw(s, ((NI)chckRange(((NI64)-(len)), ((NI) 1), ((NI) IL64(9223372036854775807)))));
			e_2 = T32_.Field0;
			rl_2 = T32_.Field1;
			nimln_(313, "unicode.nim");
			nimln_(314, "unicode.nim");
			{
				if (!(e_2 <= ((NI) 0))) goto LA35_;
				nimln_(315, "unicode.nim");
				result = copyString(((NimStringDesc*) &TM_e1RUVS0Bw7xmj9cnDPXLJMQ_9));
			}
			goto LA33_;
			LA35_: ;
			{
				NI TM_e1RUVS0Bw7xmj9cnDPXLJMQ_17;
				nimln_(317, "unicode.nim");
				TM_e1RUVS0Bw7xmj9cnDPXLJMQ_17 = subInt(e_2, ((NI) 1));
				result = copyStrLast(s, o_2, (NI)(TM_e1RUVS0Bw7xmj9cnDPXLJMQ_17));
			}
			LA33_: ;
		}
		goto LA22_;
		LA30_: ;
		{
			NI e_3;
			NI TM_e1RUVS0Bw7xmj9cnDPXLJMQ_18;
			nimln_(319, "unicode.nim");
			e_3 = runeOffset_VmqqfobaPIVf6yXE36KGjA(s, ((NI)chckRange(len, ((NI) 0), ((NI) IL64(9223372036854775807)))), ((NI)chckRange(o_2, ((NI) 0), ((NI) IL64(9223372036854775807)))));
			nimln_(320, "unicode.nim");
			{
				if (!(e_3 < ((NI) 0))) goto LA41_;
				nimln_(321, "unicode.nim");
				e_3 = (s ? s->Sup.len : 0);
			}
			LA41_: ;
			nimln_(322, "unicode.nim");
			TM_e1RUVS0Bw7xmj9cnDPXLJMQ_18 = subInt(e_3, ((NI) 1));
			result = copyStrLast(s, o_2, (NI)(TM_e1RUVS0Bw7xmj9cnDPXLJMQ_18));
		}
		LA22_: ;
	}
	LA1_: ;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_unicodeInit000)(void) {
	nimfr_("unicode", "unicode.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_unicodeDatInit000)(void) {
}

