/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\Nim\nim-0.18.0_x64\nim-0.18.0\dist\mingw64\bin\gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN -O3 -fno-strict-aliasing  -IC:\Nim\nim-0.18.0_x64\nim-0.18.0\lib -o G:\Programming\Project\Nim\nigui_examples\my_examples\nimcache\nigui_windows.o G:\Programming\Project\Nim\nigui_examples\my_examples\nimcache\nigui_windows.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct tyObject_OpenFileName_vYgl4eSybSoqlUe1vD9bfsw tyObject_OpenFileName_vYgl4eSybSoqlUe1vD9bfsw;
typedef struct tyObject_ARGB_zcvql0T8sTZjFZBZHN1Vsw tyObject_ARGB_zcvql0T8sTZjFZBZHN1Vsw;
typedef struct tyObject_RectF_4jhjakldt59cZB8eaSu3Z9aQ tyObject_RectF_4jhjakldt59cZB8eaSu3Z9aQ;
typedef struct tyObject_RGB32_eMTqFganKQ3L1Co3gEEuuA tyObject_RGB32_eMTqFganKQ3L1Co3gEEuuA;
typedef struct tyObject_Rect_VxivoY2vZJEZyWxDfx8tmQ tyObject_Rect_VxivoY2vZJEZyWxDfx8tmQ;
typedef struct tyObject_BitmapData_EyrbOtjHb52xJ5Z2G7h1Hg tyObject_BitmapData_EyrbOtjHb52xJ5Z2G7h1Hg;
typedef struct tyObject_ScrollInfo_XvgCUpbhF0LTczEK4cBhEA tyObject_ScrollInfo_XvgCUpbhF0LTczEK4cBhEA;
typedef struct tyObject_Size_Hn85q4JwVguE7xSRIlZL5A tyObject_Size_Hn85q4JwVguE7xSRIlZL5A;
typedef struct tyObject_GdiplusStartupInput_zSkasNgskGNpGAtdVxeb5w tyObject_GdiplusStartupInput_zSkasNgskGNpGAtdVxeb5w;
typedef struct tyObject_WndClassEx_kvawMPngbWf08knCEBUwXg tyObject_WndClassEx_kvawMPngbWf08knCEBUwXg;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_STDCALL_PTR(NI32, tyProc_7PnxmGgec69ahOw2euC0aMg) (NI32 CodePage, NI32 dwFlags, NCSTRING lpMultiByteStr, NI32 cbMultiByte, NCSTRING lpWideCharStr, NI32 cchWideChar);
typedef N_STDCALL_PTR(NIM_BOOL, tyProc_A0p29bQi5PzqJFgBRU8TV1g) (tyObject_OpenFileName_vYgl4eSybSoqlUe1vD9bfsw* lpofn);
typedef N_STDCALL_PTR(NI32, tyProc_aL2UbUFPf4QfHuqEKGrxGA) (NI32 CodePage, NI32 dwFlags, NCSTRING lpWideCharStr, NI32 cchWideChar, NCSTRING lpMultiByteStr, NI32 cbMultiByte, NCSTRING lpDefaultChar, void* lpUsedDefaultChar);
typedef N_STDCALL_PTR(NI32, tyProc_9bXer9a4ps9aSGctILcxWReVw) (void);
typedef N_STDCALL_PTR(NI32, tyProc_ah5wcFv3UG20t2vgXBy0Fg) (void* font);
typedef N_STDCALL_PTR(NI32, tyProc_WqUlonnXh4d6wRmtOfLenw) (NCSTRING name, void* fontCollection, void** fontFamily);
typedef N_STDCALL_PTR(NI32, tyProc_m9atr4fktDavwU2PfTzXJ1g) (void* fontFamily, float emSize, NI32 style, NI32 unit, void** font);
typedef N_STDCALL_PTR(NI32, tyProc_Ptr9a2aRIf3Nel57TUQo9cfg) (tyObject_ARGB_zcvql0T8sTZjFZBZHN1Vsw color, void** brush);
typedef N_STDCALL_PTR(NI32, tyProc_15n4BX7lBEP80RXoaK7dTA) (void* graphics, NCSTRING string, NI32 length, void* font, tyObject_RectF_4jhjakldt59cZB8eaSu3Z9aQ* layoutRect, void* stringFormat, void* brush);
typedef N_STDCALL_PTR(NI32, tyProc_L8P82WY9cuAysWAVFUx9bHDA) (tyObject_ARGB_zcvql0T8sTZjFZBZHN1Vsw color, float width, NI32 unit, void** pen);
typedef N_STDCALL_PTR(NI32, tyProc_gOjpeVmPxp0QcFSbm9bMkaA) (void* graphics, void* pen, NI32 x1, NI32 y1, NI32 x2, NI32 y2);
typedef N_STDCALL_PTR(NI32, tyProc_1ovKTH1spz8oqbNLsggw6g) (void* hdc, NI32 x, NI32 y, tyObject_RGB32_eMTqFganKQ3L1Co3gEEuuA crColor);
typedef N_STDCALL_PTR(NI32, tyProc_OtXqSp6qWQ7zT2ViJMliDQ) (void* bitmap, NI32 x, NI32 y, tyObject_ARGB_zcvql0T8sTZjFZBZHN1Vsw color);
typedef N_STDCALL_PTR(NI32, tyProc_pu56iWRuFACgjsfME4HGRA) (void* graphics, NCSTRING string, NI32 length, void* font, tyObject_RectF_4jhjakldt59cZB8eaSu3Z9aQ* layoutRect, void* stringFormat, tyObject_RectF_4jhjakldt59cZB8eaSu3Z9aQ* boundingBox, void* codepointsFitted, void* linesFilled);
typedef N_STDCALL_PTR(void*, tyProc_RJ9byCLi9cSEqbQa9a3c2uapQ) (void* hdc);
typedef N_STDCALL_PTR(NI32, tyProc_Yhyafj69ci2MHhBBSfVaSIw) (void* hdc, void** graphics);
typedef N_STDCALL_PTR(NI32, tyProc_rLd8v7s8pe8TAH0MJJwGOQ) (NI32 width, NI32 height, void* target, void** bitmap);
typedef N_STDCALL_PTR(NI32, tyProc_Wa9ahPGIzu5CD49agnphkD5Q) (NCSTRING filename, void** bitmap);
typedef N_STDCALL_PTR(NI32, tyProc_a8UZbHjFZndEEoIZvGp2ew) (void* image, NI32* width);
typedef N_STDCALL_PTR(NI32, tyProc_IMgqvg0aDoqCH3HLn09c1dw) (void* image, NCSTRING filename, void* clsidEncoder, void* encoderParams);
typedef N_STDCALL_PTR(NI32, tyProc_7tBJ5HPtDJ0QCzIO7D9aijQ) (void* bitmap, tyObject_Rect_VxivoY2vZJEZyWxDfx8tmQ* rect, NI32 flags, NI32 format, tyObject_BitmapData_EyrbOtjHb52xJ5Z2G7h1Hg* lockedBitmapData);
typedef N_STDCALL_PTR(NI32, tyProc_cAWA1Uuw9cN2sneKlFj0d8w) (void* bitmap, tyObject_BitmapData_EyrbOtjHb52xJ5Z2G7h1Hg* lockedBitmapData);
typedef N_STDCALL_PTR(NIM_BOOL, tyProc_Lw8wMv9cpxLt9c0yizTTxgEw) (void* hWnd, NIM_BOOL bEnable);
typedef N_STDCALL_PTR(NIM_BOOL, tyProc_QxJRx4bn6L9bQRLVIMMK69aA) (void* hWnd);
typedef N_STDCALL_PTR(NIM_BOOL, tyProc_hvPJxA5dIDCpNy33miQL8w) (void* hWnd, NI32 nCmdShow);
typedef N_STDCALL_PTR(void*, tyProc_eaziYd1YyguhIEtfuwqLIg) (void* hWnd, NI32 nIndex, void* dwNewLong);
typedef N_STDCALL_PTR(NI32, tyProc_xrKXh0KvZr9bKI9cyBIvoILg) (void* hWnd, NI32 nIndex, NI32 dwNewLong);
typedef N_STDCALL_PTR(NIM_BOOL, tyProc_AO9aNPNOwPeBFrb9a8L2kCyQ) (void* wnd, void* hWndInsertAfter, NI32 x, NI32 y, NI32 cx, NI32 cy, NI uFlags);
typedef N_STDCALL_PTR(void*, tyProc_U9aZ9ar83F9a9ajpOLLADtIucA) (void);
typedef N_STDCALL_PTR(NIM_BOOL, tyProc_a9bPfgdb9cxALdXRBninkMCg) (NI32 uiAction, NI32 uiParam, void* pvParam, NI32 fWinIni);
typedef N_STDCALL_PTR(NIM_BOOL, tyProc_7MyDqiXJmys6tSBWVwgNsA) (void* hWnd, NCSTRING lpString);
typedef N_STDCALL_PTR(void*, tyProc_H8IsTnWiYEk6C6lm3VL6YA) (void* hWndChild, void* hWndNewParent);
typedef N_STDCALL_PTR(void*, tyProc_atNYsIZ7r4zO1EED1pT4qg) (void* hWnd, NI32 msg, void* wParam, void* lParam);
typedef N_STDCALL_PTR(NIM_BOOL, tyProc_YyRZ5fABFs9ah7yEL1XGycw) (void* hWnd, NI32 wBar, NIM_BOOL bShow);
typedef N_STDCALL_PTR(NI32, tyProc_AwPs2JoHODRP5YXpT1WaKg) (void* hWnd, NI32 fnBar, tyObject_ScrollInfo_XvgCUpbhF0LTczEK4cBhEA* lpsi, NIM_BOOL fRedraw);
typedef N_STDCALL_PTR(NIM_BOOL, tyProc_EbscUpNtn7ymQyYiNcdKPA) (void* hWnd, tyObject_Rect_VxivoY2vZJEZyWxDfx8tmQ* lpRect, NIM_BOOL bErase);
typedef N_STDCALL_PTR(void*, tyProc_yv4aPgugqLPkw9a9cgMKKgqg) (NI32 nHeight, NI32 nWidth, NI32 nEscapement, NI32 nOrientation, NI32 fnWeight, NI32 fdwItalic, NI32 fdwUnderline, NI32 fdwStrikeOut, NI32 fdwCharSet, NI32 fdwOutputPrecision, NI32 fdwClipPrecision, NI32 fdwQuality, NI32 fdwPitchAndFamily, NCSTRING lpszFace);
typedef N_STDCALL_PTR(NIM_BOOL, tyProc_2IHhNXEwn9bxlGPtlfb9bkAA) (void* hdc, NCSTRING lpString, NI32 c, tyObject_Size_Hn85q4JwVguE7xSRIlZL5A* lpSize);
typedef N_STDCALL_PTR(NI32, tyProc_E2vEM1BUo0aogky3z9cXnGg) (void* hWnd, NCSTRING lpString, NI32 nMaxCount);
typedef N_STDCALL_PTR(NI32, tyProc_ndL2MvZ9b9bJg9cqR14Yw9cbFg) (void** token, tyObject_GdiplusStartupInput_zSkasNgskGNpGAtdVxeb5w* input, void* output);
typedef N_STDCALL_PTR(NI32, tyProc_IJ8vvlYbVRxpIZFy4xyteg) (void* lpBuffer, NI32 uSize);
typedef N_STDCALL_PTR(void*, tyProc_ZftsZIPQj8gcvKvoQpcvfg) (void* hInstance, NCSTRING lpCursorName);
typedef N_STDCALL_PTR(void*, tyProc_4LwT9bck9a2TlzUEfV3KrN9ag) (tyObject_RGB32_eMTqFganKQ3L1Co3gEEuuA crColor);
struct tyObject_RGB32_eMTqFganKQ3L1Co3gEEuuA {
NU8 red;
NU8 green;
NU8 blue;
NU8 unused;
};
typedef N_STDCALL_PTR(tyObject_RGB32_eMTqFganKQ3L1Co3gEEuuA, tyProc_gyMZMPVA3KXFO9co0rVl3pg) (NI32 nIndex);
typedef N_STDCALL_PTR(NI16, tyProc_9aPA3Nwf3SWDJZ6PJxYy39cQ) (tyObject_WndClassEx_kvawMPngbWf08knCEBUwXg* lpwcx);
typedef N_STDCALL_PTR(void*, tyProc_MiNAWAS20PBNUaLlFs0zMA) (void* hWnd, NI32 nIndex);
typedef N_STDCALL_PTR(NIM_BOOL, tyProc_ycrYbV8HnW0TXpvo7DRXHw) (void* wnd, tyObject_Rect_VxivoY2vZJEZyWxDfx8tmQ* lpRect);
typedef N_STDCALL_PTR(NI32, tyProc_XjdpNvFfnBj2lqzibYNzUw) (void* hDrop, NU32 iFile, NCSTRING lpszFile, NI32 cch);
typedef N_STDCALL_PTR(void, tyProc_im9buRnIvptJfzdASYMEbBA) (void* hDrop);
typedef N_STDCALL_PTR(NIM_BOOL, tyProc_zZOSr5NyndRfg3ncLW2lOw) (NU8* lpKeyState);
typedef N_STDCALL_PTR(NI32, tyProc_aH9bWUBLQMXdc4VL7RElsXw) (NI32 uCode, NI32 uMapType);
typedef N_STDCALL_PTR(NI32, tyProc_caKNpCnm0IEcf29aG9aS0lzA) (NI32 wVirtKey, NI32 wScanCode, NU8* lpKeyState, NCSTRING pwszBuff, NI32 cchBuff, NI32 wFlags);
typedef N_STDCALL_PTR(void*, tyProc_cdKxxPL6SfeQOfhEYGGKYQ) (void* hDlg, void* hCtl, NIM_BOOL bPrevious);
typedef N_STDCALL_PTR(tyObject_RGB32_eMTqFganKQ3L1Co3gEEuuA, tyProc_Zc9bcejqy9c0dwCZschRcebA) (void* hdc, tyObject_RGB32_eMTqFganKQ3L1Co3gEEuuA crColor);
typedef N_STDCALL_PTR(void*, tyProc_g9af9azWSgSPo0YAXp2lXQqw) (void* hWnd, NI uMsg, void* wParam, void* lParam);
typedef N_STDCALL_PTR(void*, tyProc_Fq8w9ct09bs0JvPlZzl1uIXw) (void* hWnd, NU8* lpPaint);
typedef N_STDCALL_PTR(NIM_BOOL, tyProc_cDzfAZkxY4yc5QX9bMQwQ4w) (void* hWnd, NU8* lpPaint);
typedef N_STDCALL_PTR(void*, tyProc_V1zid1YpKbgM30owGngEqw) (void* lpPrevWndFunc, void* hWnd, NI32 uMsg, void* wParam, void* lParam);
typedef N_STDCALL_PTR(NI32, tyProc_ARIal6jZ85aG9cEwvpjmQ1w) (void* hDC, tyObject_Rect_VxivoY2vZJEZyWxDfx8tmQ* lprc, void* hbr);
typedef N_STDCALL_PTR(void*, tyProc_LP9aVw9ak4ztwPG9cJDMN8H0g) (NI32 dwExStyle, NCSTRING lpClassName, NCSTRING lpWindowName, NI32 dwStyle, NI x, NI y, NI nWidth, NI nHeight, void* hWndParent, void* hMenu, void* hInstance, void* lpParam);
typedef N_STDCALL_PTR(NI32, tyProc_78ER49aUeWMW9b9c9aDqn5uqBg) (NI32 nIndex);
typedef N_STDCALL_PTR(void, tyProc_bG0Eo9aKqHnucBdwdV7fU9cw) (void* hWnd, NIM_BOOL fAccept);
typedef N_STDCALL_PTR(NI16, tyProc_m9bO4DmYzR9c3kgmXD9bY525Q) (NI32 nVirtKey);
typedef N_STDCALL_PTR(void, tyProc_KK7tXOLIne5LrthsNOelnQ) (void* hWnd, NCSTRING lpText, NCSTRING lpCaption, NI uType);
typedef N_STDCALL_PTR(NIM_BOOL, tyProc_m9bRrvNaNHombdULSq5qTgw) (void* lpMsg, void* hWnd, NI32 wMsgFilterMin, NI32 wMsgFilterMax);
struct tyObject_OpenFileName_vYgl4eSybSoqlUe1vD9bfsw {
NI32 lStructSize;
void* hwndOwner;
void* hInstance;
NCSTRING lpstrFilter;
NCSTRING lpstrCustomFilter;
NI32 nMaxCustFilter;
NI32 nFilterIndex;
NCSTRING lpstrFile;
NI32 nMaxFile;
NCSTRING lpstrFileTitle;
NI32 nMaxFileTitle;
NCSTRING lpstrInitialDir;
NCSTRING lpstrTitle;
NI32 Flags;
NI16 nFileOffset;
NI16 nFileExtension;
NCSTRING lpstrDefExt;
void* lCustData;
void* lpfnHook;
NCSTRING lpTemplateName;
};
struct tyObject_ARGB_zcvql0T8sTZjFZBZHN1Vsw {
NU8 blue;
NU8 green;
NU8 red;
NU8 alpha;
};
struct tyObject_RectF_4jhjakldt59cZB8eaSu3Z9aQ {
float x;
float y;
float width;
float height;
};
struct tyObject_Rect_VxivoY2vZJEZyWxDfx8tmQ {
NI32 left;
NI32 top;
NI32 right;
NI32 bottom;
};
struct tyObject_BitmapData_EyrbOtjHb52xJ5Z2G7h1Hg {
NI32 Width;
NI32 Height;
NI32 Stride;
NI32 PixelFormat;
NU8* Scan0;
void* Reserved;
};
struct tyObject_ScrollInfo_XvgCUpbhF0LTczEK4cBhEA {
NI32 cbSize;
NI32 fMask;
NI32 nMin;
NI32 nMax;
NI32 nPage;
NI32 nPos;
NI32 nTrackPos;
};
struct tyObject_Size_Hn85q4JwVguE7xSRIlZL5A {
NI32 cx;
NI32 cy;
};
struct tyObject_GdiplusStartupInput_zSkasNgskGNpGAtdVxeb5w {
NI32 GdiplusVersion;
void* DebugEventCallback;
NIM_BOOL SuppressBackgroundThread;
NIM_BOOL SuppressExternalCodecs;
};
struct tyObject_WndClassEx_kvawMPngbWf08knCEBUwXg {
NI32 cbSize;
NI32 style;
void* lpfnWndProc;
NI32 cbClsExtra;
NI32 cbWndExtra;
void* hInstance;
void* hIcon;
void* hCursor;
void* hbrBackground;
NCSTRING lpszMenuName;
NCSTRING lpszClassName;
void* hIconSm;
};
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* path);
N_NIMCALL(void*, nimGetProcAddr)(void* lib, NCSTRING name);
N_LIB_PRIVATE N_NIMCALL(NI, roof__quCe21GD6ES9cmTsTs9cYP7Q)(NI x, NI y);
static void* TM_9aTFEkx0c9aDHlVGqxe09bXBQ_2;
tyProc_7PnxmGgec69ahOw2euC0aMg Dl_114458_;
static void* TM_9aTFEkx0c9aDHlVGqxe09bXBQ_8;
tyProc_A0p29bQi5PzqJFgBRU8TV1g Dl_115069_;
tyProc_aL2UbUFPf4QfHuqEKGrxGA Dl_114466_;
tyProc_9bXer9a4ps9aSGctILcxWReVw Dl_115067_;
tyProc_A0p29bQi5PzqJFgBRU8TV1g Dl_115073_;
static void* TM_9aTFEkx0c9aDHlVGqxe09bXBQ_20;
tyProc_ah5wcFv3UG20t2vgXBy0Fg Dl_115028_;
tyProc_ah5wcFv3UG20t2vgXBy0Fg Dl_114984_;
tyProc_ah5wcFv3UG20t2vgXBy0Fg Dl_114994_;
tyProc_ah5wcFv3UG20t2vgXBy0Fg Dl_114907_;
tyProc_WqUlonnXh4d6wRmtOfLenw Dl_115031_;
tyProc_m9atr4fktDavwU2PfTzXJ1g Dl_115020_;
tyProc_ah5wcFv3UG20t2vgXBy0Fg Dl_115037_;
tyProc_Ptr9a2aRIf3Nel57TUQo9cfg Dl_114979_;
tyProc_15n4BX7lBEP80RXoaK7dTA Dl_114997_;
tyProc_L8P82WY9cuAysWAVFUx9bHDA Dl_114987_;
tyProc_gOjpeVmPxp0QcFSbm9bMkaA Dl_114971_;
tyProc_gOjpeVmPxp0QcFSbm9bMkaA Dl_114955_;
tyProc_gOjpeVmPxp0QcFSbm9bMkaA Dl_114963_;
tyProc_gOjpeVmPxp0QcFSbm9bMkaA Dl_114910_;
static void* TM_9aTFEkx0c9aDHlVGqxe09bXBQ_52;
tyProc_1ovKTH1spz8oqbNLsggw6g Dl_114879_;
tyProc_OtXqSp6qWQ7zT2ViJMliDQ Dl_114935_;
tyProc_pu56iWRuFACgjsfME4HGRA Dl_115007_;
tyProc_ah5wcFv3UG20t2vgXBy0Fg Dl_114952_;
tyProc_RJ9byCLi9cSEqbQa9a3c2uapQ Dl_114876_;
tyProc_Yhyafj69ci2MHhBBSfVaSIw Dl_114902_;
tyProc_rLd8v7s8pe8TAH0MJJwGOQ Dl_114928_;
tyProc_Yhyafj69ci2MHhBBSfVaSIw Dl_114947_;
tyProc_Wa9ahPGIzu5CD49agnphkD5Q Dl_114892_;
tyProc_a8UZbHjFZndEEoIZvGp2ew Dl_114918_;
tyProc_a8UZbHjFZndEEoIZvGp2ew Dl_114923_;
tyProc_IMgqvg0aDoqCH3HLn09c1dw Dl_114941_;
tyProc_7tBJ5HPtDJ0QCzIO7D9aijQ Dl_115040_;
tyProc_cAWA1Uuw9cN2sneKlFj0d8w Dl_115049_;
static void* TM_9aTFEkx0c9aDHlVGqxe09bXBQ_84;
tyProc_Lw8wMv9cpxLt9c0yizTTxgEw Dl_114523_;
tyProc_QxJRx4bn6L9bQRLVIMMK69aA Dl_114516_;
tyProc_hvPJxA5dIDCpNy33miQL8w Dl_114519_;
tyProc_eaziYd1YyguhIEtfuwqLIg Dl_114786_;
tyProc_xrKXh0KvZr9bKI9cyBIvoILg Dl_114556_;
tyProc_AO9aNPNOwPeBFrb9a8L2kCyQ Dl_114584_;
tyProc_U9aZ9ar83F9a9ajpOLLADtIucA Dl_114648_;
tyProc_a9bPfgdb9cxALdXRBninkMCg Dl_114650_;
tyProc_7MyDqiXJmys6tSBWVwgNsA Dl_114569_;
tyProc_H8IsTnWiYEk6C6lm3VL6YA Dl_114552_;
tyProc_Yhyafj69ci2MHhBBSfVaSIw Dl_114897_;
tyProc_atNYsIZ7r4zO1EED1pT4qg Dl_114624_;
tyProc_YyRZ5fABFs9ah7yEL1XGycw Dl_114726_;
tyProc_AwPs2JoHODRP5YXpT1WaKg Dl_114671_;
tyProc_EbscUpNtn7ymQyYiNcdKPA Dl_114639_;
tyProc_QxJRx4bn6L9bQRLVIMMK69aA Dl_114804_;
tyProc_yv4aPgugqLPkw9a9cgMKKgqg Dl_114830_;
tyProc_RJ9byCLi9cSEqbQa9a3c2uapQ Dl_114601_;
tyProc_RJ9byCLi9cSEqbQa9a3c2uapQ Dl_114710_;
tyProc_H8IsTnWiYEk6C6lm3VL6YA Dl_114811_;
tyProc_2IHhNXEwn9bxlGPtlfb9bkAA Dl_114846_;
tyProc_QxJRx4bn6L9bQRLVIMMK69aA Dl_114801_;
tyProc_ah5wcFv3UG20t2vgXBy0Fg Dl_114578_;
tyProc_E2vEM1BUo0aogky3z9cXnGg Dl_114573_;
tyProc_ndL2MvZ9b9bJg9cqR14Yw9cbFg Dl_114885_;
tyProc_IJ8vvlYbVRxpIZFy4xyteg Dl_114454_;
tyProc_RJ9byCLi9cSEqbQa9a3c2uapQ Dl_114447_;
tyProc_ZftsZIPQj8gcvKvoQpcvfg Dl_114667_;
tyProc_4LwT9bck9a2TlzUEfV3KrN9ag Dl_114822_;
tyProc_gyMZMPVA3KXFO9co0rVl3pg Dl_114636_;
tyProc_9aPA3Nwf3SWDJZ6PJxYy39cQ Dl_114498_;
tyProc_MiNAWAS20PBNUaLlFs0zMA Dl_114782_;
tyProc_ycrYbV8HnW0TXpvo7DRXHw Dl_114604_;
tyProc_ycrYbV8HnW0TXpvo7DRXHw Dl_114609_;
static void* TM_9aTFEkx0c9aDHlVGqxe09bXBQ_156;
tyProc_XjdpNvFfnBj2lqzibYNzUw Dl_115058_;
tyProc_im9buRnIvptJfzdASYMEbBA Dl_115064_;
tyProc_zZOSr5NyndRfg3ncLW2lOw Dl_114713_;
tyProc_aH9bWUBLQMXdc4VL7RElsXw Dl_114778_;
tyProc_caKNpCnm0IEcf29aG9aS0lzA Dl_114717_;
tyProc_cdKxxPL6SfeQOfhEYGGKYQ Dl_114702_;
tyProc_Zc9bcejqy9c0dwCZschRcebA Dl_114857_;
tyProc_MiNAWAS20PBNUaLlFs0zMA Dl_114807_;
tyProc_g9af9azWSgSPo0YAXp2lXQqw Dl_114527_;
tyProc_Fq8w9ct09bs0JvPlZzl1uIXw Dl_114614_;
tyProc_IJ8vvlYbVRxpIZFy4xyteg Dl_114853_;
tyProc_cDzfAZkxY4yc5QX9bMQwQ4w Dl_114619_;
tyProc_V1zid1YpKbgM30owGngEqw Dl_114691_;
tyProc_ARIal6jZ85aG9cEwvpjmQ1w Dl_114749_;
tyProc_LP9aVw9ak4ztwPG9cJDMN8H0g Dl_114502_;
tyProc_78ER49aUeWMW9b9c9aDqn5uqBg Dl_114688_;
tyProc_bG0Eo9aKqHnucBdwdV7fU9cw Dl_115054_;
tyProc_m9bO4DmYzR9c3kgmXD9bY525Q Dl_114761_;
tyProc_KK7tXOLIne5LrthsNOelnQ Dl_114492_;
tyProc_m9bRrvNaNHombdULSq5qTgw Dl_114533_;
tyProc_QxJRx4bn6L9bQRLVIMMK69aA Dl_114546_;
tyProc_RJ9byCLi9cSEqbQa9a3c2uapQ Dl_114549_;
STRING_LITERAL(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_4, "Kernel32.dll", 12);
STRING_LITERAL(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_5, "Kernel32.dll", 12);
STRING_LITERAL(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_10, "Comdlg32.dll", 12);
STRING_LITERAL(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_11, "Comdlg32.dll", 12);
STRING_LITERAL(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_22, "Gdiplus.dll", 11);
STRING_LITERAL(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_23, "Gdiplus.dll", 11);
STRING_LITERAL(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_54, "Gdi32.dll", 9);
STRING_LITERAL(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_55, "Gdi32.dll", 9);
STRING_LITERAL(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_86, "User32.dll", 10);
STRING_LITERAL(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_87, "User32.dll", 10);
STRING_LITERAL(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_158, "Shell32.dll", 11);
STRING_LITERAL(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_159, "Shell32.dll", 11);

N_LIB_PRIVATE N_NIMCALL(NI, hiWord_BEDTt3KWVdVGg1xnhgCElw)(void* param) {
	NI result;
	result = (NI)0;
	result = (NI)((NI)((NU64)(((NI) (ptrdiff_t) (param))) >> (NU64)(((NI) 16))) & ((NI) 65535));
	{
		NI T3_;
		NI T6_;
		T3_ = (NI)0;
		T3_ = roof__quCe21GD6ES9cmTsTs9cYP7Q(((NI) 2), ((NI) 15));
		if (!(T3_ < result)) goto LA4_;
		T6_ = (NI)0;
		T6_ = roof__quCe21GD6ES9cmTsTs9cYP7Q(((NI) 2), ((NI) 16));
		result = (NI)(result - T6_);
	}
	LA4_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, loWord_BEDTt3KWVdVGg1xnhgCElw_2)(void* param) {
	NI result;
	result = (NI)0;
	result = (NI)(((NI) (ptrdiff_t) (param)) & ((NI) 65535));
	return result;
}
NIM_EXTERNC N_NOINLINE(void, nigui_windowsInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, nigui_windowsDatInit000)(void) {
if (!((TM_9aTFEkx0c9aDHlVGqxe09bXBQ_2 = nimLoadLibrary((NimStringDesc*) &TM_9aTFEkx0c9aDHlVGqxe09bXBQ_4))
)) nimLoadLibraryError((NimStringDesc*) &TM_9aTFEkx0c9aDHlVGqxe09bXBQ_5);
	Dl_114458_ = (tyProc_7PnxmGgec69ahOw2euC0aMg) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_2, "MultiByteToWideChar");
if (!((TM_9aTFEkx0c9aDHlVGqxe09bXBQ_8 = nimLoadLibrary((NimStringDesc*) &TM_9aTFEkx0c9aDHlVGqxe09bXBQ_10))
)) nimLoadLibraryError((NimStringDesc*) &TM_9aTFEkx0c9aDHlVGqxe09bXBQ_11);
	Dl_115069_ = (tyProc_A0p29bQi5PzqJFgBRU8TV1g) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_8, "GetOpenFileNameW");
	Dl_114466_ = (tyProc_aL2UbUFPf4QfHuqEKGrxGA) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_2, "WideCharToMultiByte");
	Dl_115067_ = (tyProc_9bXer9a4ps9aSGctILcxWReVw) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_8, "CommDlgExtendedError");
	Dl_115073_ = (tyProc_A0p29bQi5PzqJFgBRU8TV1g) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_8, "GetSaveFileNameW");
if (!((TM_9aTFEkx0c9aDHlVGqxe09bXBQ_20 = nimLoadLibrary((NimStringDesc*) &TM_9aTFEkx0c9aDHlVGqxe09bXBQ_22))
)) nimLoadLibraryError((NimStringDesc*) &TM_9aTFEkx0c9aDHlVGqxe09bXBQ_23);
	Dl_115028_ = (tyProc_ah5wcFv3UG20t2vgXBy0Fg) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_20, "GdipDeleteFont");
	Dl_114984_ = (tyProc_ah5wcFv3UG20t2vgXBy0Fg) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_20, "GdipDeleteBrush");
	Dl_114994_ = (tyProc_ah5wcFv3UG20t2vgXBy0Fg) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_20, "GdipDeletePen");
	Dl_114907_ = (tyProc_ah5wcFv3UG20t2vgXBy0Fg) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_20, "GdipDeleteGraphics");
	Dl_115031_ = (tyProc_WqUlonnXh4d6wRmtOfLenw) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_20, "GdipCreateFontFamilyFromName");
	Dl_115020_ = (tyProc_m9atr4fktDavwU2PfTzXJ1g) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_20, "GdipCreateFont");
	Dl_115037_ = (tyProc_ah5wcFv3UG20t2vgXBy0Fg) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_20, "GdipDeleteFontFamily");
	Dl_114979_ = (tyProc_Ptr9a2aRIf3Nel57TUQo9cfg) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_20, "GdipCreateSolidFill");
	Dl_114997_ = (tyProc_15n4BX7lBEP80RXoaK7dTA) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_20, "GdipDrawString");
	Dl_114987_ = (tyProc_L8P82WY9cuAysWAVFUx9bHDA) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_20, "GdipCreatePen1");
	Dl_114971_ = (tyProc_gOjpeVmPxp0QcFSbm9bMkaA) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_20, "GdipDrawLineI");
	Dl_114955_ = (tyProc_gOjpeVmPxp0QcFSbm9bMkaA) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_20, "GdipFillRectangleI");
	Dl_114963_ = (tyProc_gOjpeVmPxp0QcFSbm9bMkaA) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_20, "GdipDrawRectangleI");
	Dl_114910_ = (tyProc_gOjpeVmPxp0QcFSbm9bMkaA) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_20, "GdipDrawImageRectI");
if (!((TM_9aTFEkx0c9aDHlVGqxe09bXBQ_52 = nimLoadLibrary((NimStringDesc*) &TM_9aTFEkx0c9aDHlVGqxe09bXBQ_54))
)) nimLoadLibraryError((NimStringDesc*) &TM_9aTFEkx0c9aDHlVGqxe09bXBQ_55);
	Dl_114879_ = (tyProc_1ovKTH1spz8oqbNLsggw6g) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_52, "SetPixel");
	Dl_114935_ = (tyProc_OtXqSp6qWQ7zT2ViJMliDQ) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_20, "GdipBitmapSetPixel");
	Dl_115007_ = (tyProc_pu56iWRuFACgjsfME4HGRA) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_20, "GdipMeasureString");
	Dl_114952_ = (tyProc_ah5wcFv3UG20t2vgXBy0Fg) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_20, "GdipDisposeImage");
	Dl_114876_ = (tyProc_RJ9byCLi9cSEqbQa9a3c2uapQ) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_52, "CreateCompatibleDC");
	Dl_114902_ = (tyProc_Yhyafj69ci2MHhBBSfVaSIw) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_20, "GdipCreateFromHDC");
	Dl_114928_ = (tyProc_rLd8v7s8pe8TAH0MJJwGOQ) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_20, "GdipCreateBitmapFromGraphics");
	Dl_114947_ = (tyProc_Yhyafj69ci2MHhBBSfVaSIw) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_20, "GdipGetImageGraphicsContext");
	Dl_114892_ = (tyProc_Wa9ahPGIzu5CD49agnphkD5Q) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_20, "GdipCreateBitmapFromFile");
	Dl_114918_ = (tyProc_a8UZbHjFZndEEoIZvGp2ew) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_20, "GdipGetImageWidth");
	Dl_114923_ = (tyProc_a8UZbHjFZndEEoIZvGp2ew) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_20, "GdipGetImageHeight");
	Dl_114941_ = (tyProc_IMgqvg0aDoqCH3HLn09c1dw) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_20, "GdipSaveImageToFile");
	Dl_115040_ = (tyProc_7tBJ5HPtDJ0QCzIO7D9aijQ) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_20, "GdipBitmapLockBits");
	Dl_115049_ = (tyProc_cAWA1Uuw9cN2sneKlFj0d8w) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_20, "GdipBitmapUnlockBits");
if (!((TM_9aTFEkx0c9aDHlVGqxe09bXBQ_84 = nimLoadLibrary((NimStringDesc*) &TM_9aTFEkx0c9aDHlVGqxe09bXBQ_86))
)) nimLoadLibraryError((NimStringDesc*) &TM_9aTFEkx0c9aDHlVGqxe09bXBQ_87);
	Dl_114523_ = (tyProc_Lw8wMv9cpxLt9c0yizTTxgEw) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_84, "EnableWindow");
	Dl_114516_ = (tyProc_QxJRx4bn6L9bQRLVIMMK69aA) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_84, "DestroyWindow");
	Dl_114519_ = (tyProc_hvPJxA5dIDCpNy33miQL8w) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_84, "ShowWindow");
	Dl_114786_ = (tyProc_eaziYd1YyguhIEtfuwqLIg) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_84, "SetWindowLongPtrW");
	Dl_114556_ = (tyProc_xrKXh0KvZr9bKI9cyBIvoILg) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_84, "SetWindowLongA");
	Dl_114584_ = (tyProc_AO9aNPNOwPeBFrb9a8L2kCyQ) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_84, "SetWindowPos");
	Dl_114648_ = (tyProc_U9aZ9ar83F9a9ajpOLLADtIucA) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_84, "GetDesktopWindow");
	Dl_114650_ = (tyProc_a9bPfgdb9cxALdXRBninkMCg) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_84, "SystemParametersInfoA");
	Dl_114569_ = (tyProc_7MyDqiXJmys6tSBWVwgNsA) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_84, "SetWindowTextW");
	Dl_114552_ = (tyProc_H8IsTnWiYEk6C6lm3VL6YA) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_84, "SetParent");
	Dl_114897_ = (tyProc_Yhyafj69ci2MHhBBSfVaSIw) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_20, "GdipCreateHICONFromBitmap");
	Dl_114624_ = (tyProc_atNYsIZ7r4zO1EED1pT4qg) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_84, "SendMessageA");
	Dl_114726_ = (tyProc_YyRZ5fABFs9ah7yEL1XGycw) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_84, "ShowScrollBar");
	Dl_114671_ = (tyProc_AwPs2JoHODRP5YXpT1WaKg) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_84, "SetScrollInfo");
	Dl_114639_ = (tyProc_EbscUpNtn7ymQyYiNcdKPA) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_84, "InvalidateRect");
	Dl_114804_ = (tyProc_QxJRx4bn6L9bQRLVIMMK69aA) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_52, "DeleteObject");
	Dl_114830_ = (tyProc_yv4aPgugqLPkw9a9cgMKKgqg) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_52, "CreateFontA");
	Dl_114601_ = (tyProc_RJ9byCLi9cSEqbQa9a3c2uapQ) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_84, "SetFocus");
	Dl_114710_ = (tyProc_RJ9byCLi9cSEqbQa9a3c2uapQ) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_84, "GetDC");
	Dl_114811_ = (tyProc_H8IsTnWiYEk6C6lm3VL6YA) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_52, "SelectObject");
	Dl_114846_ = (tyProc_2IHhNXEwn9bxlGPtlfb9bkAA) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_52, "GetTextExtentPoint32W");
	Dl_114801_ = (tyProc_QxJRx4bn6L9bQRLVIMMK69aA) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_52, "DeleteDC");
	Dl_114578_ = (tyProc_ah5wcFv3UG20t2vgXBy0Fg) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_84, "GetWindowTextLengthW");
	Dl_114573_ = (tyProc_E2vEM1BUo0aogky3z9cXnGg) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_84, "GetWindowTextW");
	Dl_114885_ = (tyProc_ndL2MvZ9b9bJg9cqR14Yw9cbFg) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_20, "GdiplusStartup");
	Dl_114454_ = (tyProc_IJ8vvlYbVRxpIZFy4xyteg) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_2, "GetSystemDirectoryA");
	Dl_114447_ = (tyProc_RJ9byCLi9cSEqbQa9a3c2uapQ) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_2, "CreateActCtxA");
	Dl_114667_ = (tyProc_ZftsZIPQj8gcvKvoQpcvfg) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_84, "LoadCursorA");
	Dl_114822_ = (tyProc_4LwT9bck9a2TlzUEfV3KrN9ag) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_52, "CreateSolidBrush");
	Dl_114636_ = (tyProc_gyMZMPVA3KXFO9co0rVl3pg) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_84, "GetSysColor");
	Dl_114498_ = (tyProc_9aPA3Nwf3SWDJZ6PJxYy39cQ) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_84, "RegisterClassExA");
	Dl_114782_ = (tyProc_MiNAWAS20PBNUaLlFs0zMA) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_84, "GetWindowLongPtrW");
	Dl_114604_ = (tyProc_ycrYbV8HnW0TXpvo7DRXHw) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_84, "GetWindowRect");
	Dl_114609_ = (tyProc_ycrYbV8HnW0TXpvo7DRXHw) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_84, "GetClientRect");
if (!((TM_9aTFEkx0c9aDHlVGqxe09bXBQ_156 = nimLoadLibrary((NimStringDesc*) &TM_9aTFEkx0c9aDHlVGqxe09bXBQ_158))
)) nimLoadLibraryError((NimStringDesc*) &TM_9aTFEkx0c9aDHlVGqxe09bXBQ_159);
	Dl_115058_ = (tyProc_XjdpNvFfnBj2lqzibYNzUw) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_156, "DragQueryFileW");
	Dl_115064_ = (tyProc_im9buRnIvptJfzdASYMEbBA) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_156, "DragFinish");
	Dl_114713_ = (tyProc_zZOSr5NyndRfg3ncLW2lOw) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_84, "GetKeyboardState");
	Dl_114778_ = (tyProc_aH9bWUBLQMXdc4VL7RElsXw) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_84, "MapVirtualKeyW");
	Dl_114717_ = (tyProc_caKNpCnm0IEcf29aG9aS0lzA) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_84, "ToUnicode");
	Dl_114702_ = (tyProc_cdKxxPL6SfeQOfhEYGGKYQ) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_84, "GetNextDlgTabItem");
	Dl_114857_ = (tyProc_Zc9bcejqy9c0dwCZschRcebA) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_52, "SetTextColor");
	Dl_114807_ = (tyProc_MiNAWAS20PBNUaLlFs0zMA) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_52, "GetCurrentObject");
	Dl_114527_ = (tyProc_g9af9azWSgSPo0YAXp2lXQqw) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_84, "DefWindowProcA");
	Dl_114614_ = (tyProc_Fq8w9ct09bs0JvPlZzl1uIXw) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_84, "BeginPaint");
	Dl_114853_ = (tyProc_IJ8vvlYbVRxpIZFy4xyteg) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_52, "SetBkMode");
	Dl_114619_ = (tyProc_cDzfAZkxY4yc5QX9bMQwQ4w) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_84, "EndPaint");
	Dl_114691_ = (tyProc_V1zid1YpKbgM30owGngEqw) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_84, "CallWindowProcW");
	Dl_114749_ = (tyProc_ARIal6jZ85aG9cEwvpjmQ1w) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_84, "FillRect");
	Dl_114502_ = (tyProc_LP9aVw9ak4ztwPG9cJDMN8H0g) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_84, "CreateWindowExA");
	Dl_114688_ = (tyProc_78ER49aUeWMW9b9c9aDqn5uqBg) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_84, "GetSystemMetrics");
	Dl_115054_ = (tyProc_bG0Eo9aKqHnucBdwdV7fU9cw) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_156, "DragAcceptFiles");
	Dl_114761_ = (tyProc_m9bO4DmYzR9c3kgmXD9bY525Q) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_84, "GetKeyState");
	Dl_114492_ = (tyProc_KK7tXOLIne5LrthsNOelnQ) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_84, "MessageBoxW");
	Dl_114533_ = (tyProc_m9bRrvNaNHombdULSq5qTgw) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_84, "GetMessageA");
	Dl_114546_ = (tyProc_QxJRx4bn6L9bQRLVIMMK69aA) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_84, "TranslateMessage");
	Dl_114549_ = (tyProc_RJ9byCLi9cSEqbQa9a3c2uapQ) nimGetProcAddr(TM_9aTFEkx0c9aDHlVGqxe09bXBQ_84, "DispatchMessageA");
}

