/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\Nim\nim-0.18.0_x64\nim-0.18.0\dist\mingw64\bin\gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN  -IC:\Nim\nim-0.18.0_x64\nim-0.18.0\lib -o C:\Users\hkota\@Programming_projects\Nim\nigui_examples\my_examples\nimcache\stdlib_locks.o C:\Users\hkota\@Programming_projects\Nim\nigui_examples\my_examples\nimcache\stdlib_locks.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <windows.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_STDCALL_PTR(NI, tyProc_KeCiSdV9aG0JRdXpLIxCQ9cQ) (void* lpEventAttributes, NI32 bManualReset, NI32 bInitialState, NCSTRING lpName);
typedef N_STDCALL_PTR(void, tyProc_ofoySXaAAlxxs9bQS9a1etlg) (NI hObject);
typedef N_STDCALL_PTR(NI32, tyProc_FprzxJFfqQdWyyGxiUsmeQ) (NI hHandle, NI32 dwMilliseconds);
static N_INLINE(NIM_BOOL, tryAcquireSys_1IhqNgQW3p2BHbc9bb4WjNAlocks)(CRITICAL_SECTION* L);
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* path);
N_NIMCALL(void*, nimGetProcAddr)(void* lib, NCSTRING name);
static N_INLINE(void, initSysCond_05dikp5SjY49b5qLvlucEZglocks)(NI* cond);
static N_INLINE(void, deinitSysCond_05dikp5SjY49b5qLvlucEZg_2locks)(NI* cond);
N_LIB_PRIVATE N_NIMCALL(void, waitSysCond_m9bKYHzrEzSKf0WFiiK5huw)(NI* cond, CRITICAL_SECTION* lock);
N_LIB_PRIVATE N_NIMCALL(void, waitSysCondWindows_FIpIuhuN2u8V5BcL9cF69aWA)(NI* cond);
static N_INLINE(void, initLock_NXoRcxfV39aV9cflSTUwtJ1glocks)(CRITICAL_SECTION* lock);
static N_INLINE(void, deinitLock_NXoRcxfV39aV9cflSTUwtJ1g_2locks)(CRITICAL_SECTION* lock);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, tryAcquire_RVpMCi0dWU5mH1GyAP2R5w)(CRITICAL_SECTION* lock);
N_LIB_PRIVATE N_NIMCALL(void, acquire_9bBEZeGCRkWQl9bLT1qt423Q)(CRITICAL_SECTION* lock);
N_LIB_PRIVATE N_NIMCALL(void, release_9bBEZeGCRkWQl9bLT1qt423Q_2)(CRITICAL_SECTION* lock);
static N_INLINE(void, initCond_05dikp5SjY49b5qLvlucEZg_3locks)(NI* cond);
static N_INLINE(void, deinitCond_05dikp5SjY49b5qLvlucEZg_4locks)(NI* cond);
static N_INLINE(void, wait_Lc8rxHP8fVJMsOe9cdzwpuAlocks)(NI* cond, CRITICAL_SECTION* lock);
static N_INLINE(void, signal_05dikp5SjY49b5qLvlucEZg_5locks)(NI* cond);
static void* TM_05xOtLU9bCAYnon4m09bcBlg_2;
tyProc_KeCiSdV9aG0JRdXpLIxCQ9cQ Dl_64644_;
tyProc_ofoySXaAAlxxs9bQS9a1etlg Dl_64650_;
tyProc_FprzxJFfqQdWyyGxiUsmeQ Dl_64653_;
tyProc_ofoySXaAAlxxs9bQS9a1etlg Dl_64657_;
STRING_LITERAL(TM_05xOtLU9bCAYnon4m09bcBlg_4, "kernel32", 8);
STRING_LITERAL(TM_05xOtLU9bCAYnon4m09bcBlg_5, "kernel32", 8);

static N_INLINE(NIM_BOOL, tryAcquireSys_1IhqNgQW3p2BHbc9bb4WjNAlocks)(CRITICAL_SECTION* L) {
	NIM_BOOL result;
	NI32 T1_;
	result = (NIM_BOOL)0;
	T1_ = (NI32)0;
	T1_ = TryEnterCriticalSection(L);
	result = !((T1_ == ((NI32) 0)));
	return result;
}

static N_INLINE(void, initSysCond_05dikp5SjY49b5qLvlucEZglocks)(NI* cond) {
	(*cond) = Dl_64644_(NIM_NIL, ((NI32) 0), ((NI32) 0), NIM_NIL);
}

static N_INLINE(void, deinitSysCond_05dikp5SjY49b5qLvlucEZg_2locks)(NI* cond) {
	Dl_64650_((*cond));
}

N_LIB_PRIVATE N_NIMCALL(void, waitSysCond_m9bKYHzrEzSKf0WFiiK5huw)(NI* cond, CRITICAL_SECTION* lock) {
	NI32 T1_;
	LeaveCriticalSection(lock);
	T1_ = (NI32)0;
	T1_ = Dl_64653_((*cond), ((NI32) -1));
	T1_;
	EnterCriticalSection(lock);
}

N_LIB_PRIVATE N_NIMCALL(void, waitSysCondWindows_FIpIuhuN2u8V5BcL9cF69aWA)(NI* cond) {
	NI32 T1_;
	T1_ = (NI32)0;
	T1_ = Dl_64653_((*cond), ((NI32) -1));
	T1_;
}

static N_INLINE(void, initLock_NXoRcxfV39aV9cflSTUwtJ1glocks)(CRITICAL_SECTION* lock) {
	InitializeCriticalSection(lock);
}

static N_INLINE(void, deinitLock_NXoRcxfV39aV9cflSTUwtJ1g_2locks)(CRITICAL_SECTION* lock) {
	DeleteCriticalSection(lock);
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, tryAcquire_RVpMCi0dWU5mH1GyAP2R5w)(CRITICAL_SECTION* lock) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	result = tryAcquireSys_1IhqNgQW3p2BHbc9bb4WjNAlocks(lock);
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, acquire_9bBEZeGCRkWQl9bLT1qt423Q)(CRITICAL_SECTION* lock) {
	EnterCriticalSection(lock);
}

N_LIB_PRIVATE N_NIMCALL(void, release_9bBEZeGCRkWQl9bLT1qt423Q_2)(CRITICAL_SECTION* lock) {
	LeaveCriticalSection(lock);
}

static N_INLINE(void, initCond_05dikp5SjY49b5qLvlucEZg_3locks)(NI* cond) {
	initSysCond_05dikp5SjY49b5qLvlucEZglocks(cond);
}

static N_INLINE(void, deinitCond_05dikp5SjY49b5qLvlucEZg_4locks)(NI* cond) {
	deinitSysCond_05dikp5SjY49b5qLvlucEZg_2locks(cond);
}

static N_INLINE(void, wait_Lc8rxHP8fVJMsOe9cdzwpuAlocks)(NI* cond, CRITICAL_SECTION* lock) {
	waitSysCond_m9bKYHzrEzSKf0WFiiK5huw(cond, lock);
}

static N_INLINE(void, signal_05dikp5SjY49b5qLvlucEZg_5locks)(NI* cond) {
	Dl_64657_((*cond));
}
NIM_EXTERNC N_NOINLINE(void, stdlib_locksInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, stdlib_locksDatInit000)(void) {
if (!((TM_05xOtLU9bCAYnon4m09bcBlg_2 = nimLoadLibrary((NimStringDesc*) &TM_05xOtLU9bCAYnon4m09bcBlg_4))
)) nimLoadLibraryError((NimStringDesc*) &TM_05xOtLU9bCAYnon4m09bcBlg_5);
	Dl_64644_ = (tyProc_KeCiSdV9aG0JRdXpLIxCQ9cQ) nimGetProcAddr(TM_05xOtLU9bCAYnon4m09bcBlg_2, "CreateEventA");
	Dl_64650_ = (tyProc_ofoySXaAAlxxs9bQS9a1etlg) nimGetProcAddr(TM_05xOtLU9bCAYnon4m09bcBlg_2, "CloseHandle");
	Dl_64653_ = (tyProc_FprzxJFfqQdWyyGxiUsmeQ) nimGetProcAddr(TM_05xOtLU9bCAYnon4m09bcBlg_2, "WaitForSingleObject");
	Dl_64657_ = (tyProc_ofoySXaAAlxxs9bQS9a1etlg) nimGetProcAddr(TM_05xOtLU9bCAYnon4m09bcBlg_2, "SetEvent");
}

