/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\Nim\nim-0.18.0_x64\nim-0.18.0\dist\mingw64\bin\gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN -O3 -fno-strict-aliasing  -IC:\Nim\nim-0.18.0_x64\nim-0.18.0\lib -o G:\Programming\Project\Nim\nigui_examples\my_examples\nimcache\stdlib_tables.o G:\Programming\Project\Nim\nigui_examples\my_examples\nimcache\stdlib_tables.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_Table_TU9ayGijwYDpTg1thSSqo9cg tyObject_Table_TU9ayGijwYDpTg1thSSqo9cg;
typedef struct tySequence_63PnD6A6cP3Lf2gDOtuoig tySequence_63PnD6A6cP3Lf2gDOtuoig;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyTuple_gnxAzkWHXyGbTTlgBpS65Q tyTuple_gnxAzkWHXyGbTTlgBpS65Q;
typedef struct tyObject_TimerEntry_z9aNGN5Rtmhr7usPsSEw6GQ tyObject_TimerEntry_z9aNGN5Rtmhr7usPsSEw6GQ;
typedef struct tyObject_TimerEventcolonObjectType__wnv00NGl2sDOJsAGTpBNnw tyObject_TimerEventcolonObjectType__wnv00NGl2sDOJsAGTpBNnw;
typedef struct TGenericSeq TGenericSeq;
struct tyObject_Table_TU9ayGijwYDpTg1thSSqo9cg {
tySequence_63PnD6A6cP3Lf2gDOtuoig* data;
NI counter;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (tyObject_TimerEventcolonObjectType__wnv00NGl2sDOJsAGTpBNnw* event, void* ClE_0);
void* ClE_0;
} tyProc_rVMTth349c7k44sPDCKI25Q;
struct tyObject_TimerEntry_z9aNGN5Rtmhr7usPsSEw6GQ {
tyProc_rVMTth349c7k44sPDCKI25Q timerProc;
void* data;
};
struct tyTuple_gnxAzkWHXyGbTTlgBpS65Q {
NI Field0;
NI64 Field1;
tyObject_TimerEntry_z9aNGN5Rtmhr7usPsSEw6GQ Field2;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct tyObject_TimerEventcolonObjectType__wnv00NGl2sDOJsAGTpBNnw {
NI timer;
void* data;
};
struct tySequence_63PnD6A6cP3Lf2gDOtuoig {
  TGenericSeq Sup;
  tyTuple_gnxAzkWHXyGbTTlgBpS65Q data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tySequence_63PnD6A6cP3Lf2gDOtuoig)(void* p, NI op);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
TNimType NTI_TU9ayGijwYDpTg1thSSqo9cg_;
TNimType NTI_gnxAzkWHXyGbTTlgBpS65Q_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
extern TNimType NTI_Aav8dQoMlCFnZRxA0IhTHQ_;
extern TNimType NTI_z9aNGN5Rtmhr7usPsSEw6GQ_;
TNimType NTI_63PnD6A6cP3Lf2gDOtuoig_;
static N_NIMCALL(void, Marker_tySequence_63PnD6A6cP3Lf2gDOtuoig)(void* p, NI op) {
	tySequence_63PnD6A6cP3Lf2gDOtuoig* a;
	NI T1_;
	a = (tySequence_63PnD6A6cP3Lf2gDOtuoig*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < a->Sup.len; T1_++) {
	nimGCvisit((void*)a->data[T1_].Field2.timerProc.ClE_0, op);
	}
}

N_LIB_PRIVATE N_NIMCALL(void, initTable_bPmQLESwRuPjQMNeQmoOUg)(NI initialSize, tyObject_Table_TU9ayGijwYDpTg1thSSqo9cg* Result) {
	genericReset((void*)Result, (&NTI_TU9ayGijwYDpTg1thSSqo9cg_));
	(*Result).counter = ((NI) 0);
	unsureAsgnRef((void**) (&(*Result).data), (tySequence_63PnD6A6cP3Lf2gDOtuoig*) newSeq((&NTI_63PnD6A6cP3Lf2gDOtuoig_), ((NI) (initialSize))));
}
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, stdlib_tablesDatInit000)(void) {
static TNimNode* TM_4SoG2KRQy3oMm9aUzSLtGrA_2[2];
static TNimNode* TM_4SoG2KRQy3oMm9aUzSLtGrA_3[3];
static TNimNode TM_4SoG2KRQy3oMm9aUzSLtGrA_0[7];
NTI_TU9ayGijwYDpTg1thSSqo9cg_.size = sizeof(tyObject_Table_TU9ayGijwYDpTg1thSSqo9cg);
NTI_TU9ayGijwYDpTg1thSSqo9cg_.kind = 18;
NTI_TU9ayGijwYDpTg1thSSqo9cg_.base = 0;
TM_4SoG2KRQy3oMm9aUzSLtGrA_2[0] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[1];
NTI_gnxAzkWHXyGbTTlgBpS65Q_.size = sizeof(tyTuple_gnxAzkWHXyGbTTlgBpS65Q);
NTI_gnxAzkWHXyGbTTlgBpS65Q_.kind = 18;
NTI_gnxAzkWHXyGbTTlgBpS65Q_.base = 0;
TM_4SoG2KRQy3oMm9aUzSLtGrA_3[0] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[3];
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[3].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[3].offset = offsetof(tyTuple_gnxAzkWHXyGbTTlgBpS65Q, Field0);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[3].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[3].name = "Field0";
TM_4SoG2KRQy3oMm9aUzSLtGrA_3[1] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[4];
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[4].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[4].offset = offsetof(tyTuple_gnxAzkWHXyGbTTlgBpS65Q, Field1);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[4].typ = (&NTI_Aav8dQoMlCFnZRxA0IhTHQ_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[4].name = "Field1";
TM_4SoG2KRQy3oMm9aUzSLtGrA_3[2] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[5];
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[5].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[5].offset = offsetof(tyTuple_gnxAzkWHXyGbTTlgBpS65Q, Field2);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[5].typ = (&NTI_z9aNGN5Rtmhr7usPsSEw6GQ_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[5].name = "Field2";
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[2].len = 3; TM_4SoG2KRQy3oMm9aUzSLtGrA_0[2].kind = 2; TM_4SoG2KRQy3oMm9aUzSLtGrA_0[2].sons = &TM_4SoG2KRQy3oMm9aUzSLtGrA_3[0];
NTI_gnxAzkWHXyGbTTlgBpS65Q_.node = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[2];
NTI_63PnD6A6cP3Lf2gDOtuoig_.size = sizeof(tySequence_63PnD6A6cP3Lf2gDOtuoig*);
NTI_63PnD6A6cP3Lf2gDOtuoig_.kind = 24;
NTI_63PnD6A6cP3Lf2gDOtuoig_.base = (&NTI_gnxAzkWHXyGbTTlgBpS65Q_);
NTI_63PnD6A6cP3Lf2gDOtuoig_.marker = Marker_tySequence_63PnD6A6cP3Lf2gDOtuoig;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[1].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[1].offset = offsetof(tyObject_Table_TU9ayGijwYDpTg1thSSqo9cg, data);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[1].typ = (&NTI_63PnD6A6cP3Lf2gDOtuoig_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[1].name = "data";
TM_4SoG2KRQy3oMm9aUzSLtGrA_2[1] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[6];
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[6].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[6].offset = offsetof(tyObject_Table_TU9ayGijwYDpTg1thSSqo9cg, counter);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[6].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[6].name = "counter";
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[0].len = 2; TM_4SoG2KRQy3oMm9aUzSLtGrA_0[0].kind = 2; TM_4SoG2KRQy3oMm9aUzSLtGrA_0[0].sons = &TM_4SoG2KRQy3oMm9aUzSLtGrA_2[0];
NTI_TU9ayGijwYDpTg1thSSqo9cg_.node = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[0];
}

