/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\Nim\nim-0.18.0_x64\nim-0.18.0\dist\mingw64\bin\gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN -O3 -fno-strict-aliasing  -IC:\Nim\nim-0.18.0_x64\nim-0.18.0\lib -o G:\Programming\Project\Nim\nigui_examples\my_examples\nimcache\stdlib_unicode.o G:\Programming\Project\Nim\nigui_examples\my_examples\nimcache\stdlib_unicode.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ {
NI Field0;
NI Field1;
};
N_LIB_PRIVATE N_NIMCALL(tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ, runeReverseOffset_0YT8d2knu9a0zJ2Qi8H3lsw)(NimStringDesc* s, NI rev);
N_LIB_PRIVATE N_NIMCALL(NI, runeLenAt_8Ayuto32FxMnanfOP52vKg)(NimStringDesc* s, NI i);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_LIB_PRIVATE N_NIMCALL(NI, runeOffset_VmqqfobaPIVf6yXE36KGjA)(NimStringDesc* s, NI pos, NI start);
STRING_LITERAL(TM_e1RUVS0Bw7xmj9cnDPXLJMQ_2, "", 0);

N_LIB_PRIVATE N_NIMCALL(NI, runeLenAt_8Ayuto32FxMnanfOP52vKg)(NimStringDesc* s, NI i) {
	NI result;
	result = (NI)0;
	{
		if (!((NU64)(((NU8)(s->data[i]))) <= (NU64)(((NI) 127)))) goto LA3_;
		result = ((NI) 1);
	}
	goto LA1_;
	LA3_: ;
	{
		if (!((NI)((NU64)(((NU8)(s->data[i]))) >> (NU64)(((NI) 5))) == ((NI) 6))) goto LA6_;
		result = ((NI) 2);
	}
	goto LA1_;
	LA6_: ;
	{
		if (!((NI)((NU64)(((NU8)(s->data[i]))) >> (NU64)(((NI) 4))) == ((NI) 14))) goto LA9_;
		result = ((NI) 3);
	}
	goto LA1_;
	LA9_: ;
	{
		if (!((NI)((NU64)(((NU8)(s->data[i]))) >> (NU64)(((NI) 3))) == ((NI) 30))) goto LA12_;
		result = ((NI) 4);
	}
	goto LA1_;
	LA12_: ;
	{
		if (!((NI)((NU64)(((NU8)(s->data[i]))) >> (NU64)(((NI) 2))) == ((NI) 62))) goto LA15_;
		result = ((NI) 5);
	}
	goto LA1_;
	LA15_: ;
	{
		if (!((NI)((NU64)(((NU8)(s->data[i]))) >> (NU64)(((NI) 1))) == ((NI) 126))) goto LA18_;
		result = ((NI) 6);
	}
	goto LA1_;
	LA18_: ;
	{
		result = ((NI) 1);
	}
	LA1_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ, runeReverseOffset_0YT8d2knu9a0zJ2Qi8H3lsw)(NimStringDesc* s, NI rev) {
	tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ result;
	NI a;
	NI o;
	NI x;
{	memset((void*)(&result), 0, sizeof(result));
	a = ((NI) (rev));
	o = ((NI) 0);
	x = ((NI) 0);
	{
		while (1) {
			NI r;
			if (!(o < (s ? s->Sup.len : 0))) goto LA2;
			r = runeLenAt_8Ayuto32FxMnanfOP52vKg(s, ((NI) (o)));
			o += r;
			{
				if (!(a < ((NI) 0))) goto LA5_;
				x += r;
			}
			LA5_: ;
			a -= ((NI) 1);
		} LA2: ;
	}
	{
		if (!(((NI) 0) < a)) goto LA9_;
		result.Field0 = ((NI64)-(a));
		result.Field1 = (NI)(((NI) (rev)) - a);
		goto BeforeRet_;
	}
	LA9_: ;
	result.Field0 = x;
	result.Field1 = (NI)(((NI64)-(a)) + ((NI) (rev)));
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, runeOffset_VmqqfobaPIVf6yXE36KGjA)(NimStringDesc* s, NI pos, NI start) {
	NI result;
	NI i;
	NI o;
{	result = (NI)0;
	i = ((NI) 0);
	o = start;
	{
		while (1) {
			NI T3_;
			if (!(i < ((NI) (pos)))) goto LA2;
			T3_ = (NI)0;
			T3_ = runeLenAt_8Ayuto32FxMnanfOP52vKg(s, o);
			o += ((NI) (T3_));
			{
				if (!((s ? s->Sup.len : 0) <= ((NI) (o)))) goto LA6_;
				result = ((NI) -1);
				goto BeforeRet_;
			}
			LA6_: ;
			i += ((NI) 1);
		} LA2: ;
	}
	result = ((NI) (o));
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, runeSubStr_UlchVxVCtLbl0rRbUzNKXA)(NimStringDesc* s, NI pos, NI len) {
	NimStringDesc* result;
	result = (NimStringDesc*)0;
	{
		tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ T5_;
		NI o;
		NI rl;
		if (!(pos < ((NI) 0))) goto LA3_;
		T5_ = runeReverseOffset_0YT8d2knu9a0zJ2Qi8H3lsw(s, ((NI) (((NI64)-(pos)))));
		o = T5_.Field0;
		rl = T5_.Field1;
		{
			if (!(rl <= len)) goto LA8_;
			result = copyStrLast(s, o, (NI)((s ? s->Sup.len : 0) - ((NI) 1)));
		}
		goto LA6_;
		LA8_: ;
		{
			NI e;
			if (!(len < ((NI) 0))) goto LA11_;
			e = (NI)(rl + len);
			{
				if (!(e < ((NI) 0))) goto LA15_;
				result = copyString(((NimStringDesc*) &TM_e1RUVS0Bw7xmj9cnDPXLJMQ_2));
			}
			goto LA13_;
			LA15_: ;
			{
				NI T18_;
				T18_ = (NI)0;
				T18_ = runeOffset_VmqqfobaPIVf6yXE36KGjA(s, ((NI) ((NI)(e - (NI)(rl + pos)))), ((NI) (o)));
				result = copyStrLast(s, o, (NI)(T18_ - ((NI) 1)));
			}
			LA13_: ;
		}
		goto LA6_;
		LA11_: ;
		{
			NI T20_;
			T20_ = (NI)0;
			T20_ = runeOffset_VmqqfobaPIVf6yXE36KGjA(s, ((NI) (len)), ((NI) (o)));
			result = copyStrLast(s, o, (NI)(T20_ - ((NI) 1)));
		}
		LA6_: ;
	}
	goto LA1_;
	LA3_: ;
	{
		NI o_2;
		o_2 = runeOffset_VmqqfobaPIVf6yXE36KGjA(s, ((NI) (pos)), ((NI) 0));
		{
			if (!(o_2 < ((NI) 0))) goto LA24_;
			result = copyString(((NimStringDesc*) &TM_e1RUVS0Bw7xmj9cnDPXLJMQ_2));
		}
		goto LA22_;
		LA24_: ;
		{
			if (!(len == ((NI) IL64(9223372036854775807)))) goto LA27_;
			result = copyStrLast(s, o_2, (NI)((s ? s->Sup.len : 0) - ((NI) 1)));
		}
		goto LA22_;
		LA27_: ;
		{
			tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ T32_;
			NI e_2;
			NI rl_2;
			if (!(len < ((NI) 0))) goto LA30_;
			T32_ = runeReverseOffset_0YT8d2knu9a0zJ2Qi8H3lsw(s, ((NI) (((NI64)-(len)))));
			e_2 = T32_.Field0;
			rl_2 = T32_.Field1;
			{
				if (!(e_2 <= ((NI) 0))) goto LA35_;
				result = copyString(((NimStringDesc*) &TM_e1RUVS0Bw7xmj9cnDPXLJMQ_2));
			}
			goto LA33_;
			LA35_: ;
			{
				result = copyStrLast(s, o_2, (NI)(e_2 - ((NI) 1)));
			}
			LA33_: ;
		}
		goto LA22_;
		LA30_: ;
		{
			NI e_3;
			e_3 = runeOffset_VmqqfobaPIVf6yXE36KGjA(s, ((NI) (len)), ((NI) (o_2)));
			{
				if (!(e_3 < ((NI) 0))) goto LA41_;
				e_3 = (s ? s->Sup.len : 0);
			}
			LA41_: ;
			result = copyStrLast(s, o_2, (NI)(e_3 - ((NI) 1)));
		}
		LA22_: ;
	}
	LA1_: ;
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_unicodeInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, stdlib_unicodeDatInit000)(void) {
}

